SimpleOrbitDataDisplay
GameObject SimpleOrbitDataDisplay.apoapsis
Referenced by Start.
GameObject SimpleOrbitDataDisplay.periapsis
Referenced by Start.
GameObject SimpleOrbitDataDisplay.orbitDataRectParent
Referenced by Start.
float SimpleOrbitDataDisplay.textScaleAmount
Referenced by LateUpdate.
KeplerOrbitMover SimpleOrbitDataDisplay.keplerOrbitMover
Referenced by ShowSimpleOrbitData, Start, Update.
GameObject SimpleOrbitDataDisplay.tracking
string SimpleOrbitDataDisplay.apoapsisName
Referenced by Start.
string SimpleOrbitDataDisplay.periapsisName
Referenced by Start.
void SimpleOrbitDataDisplay.Start()
References apoapsis, apoapsisName, keplerOrbitMover, orbitDataRectParent, periapsis, periapsisName.
void SimpleOrbitDataDisplay.Update()
References SimpleKeplerOrbits.KeplerOrbitData.Apoapsis, keplerOrbitMover, SimpleKeplerOrbits.KeplerOrbitMover.OrbitData, SimpleKeplerOrbits.KeplerOrbitData.Periapsis, ShowSimpleOrbitData, UnityEngine.Vector3d.x, UnityEngine.Vector3d.y.
void SimpleOrbitDataDisplay.LateUpdate()
References FaceCamera, ScaleTextWithScreen, textScaleAmount.
void SimpleOrbitDataDisplay.ShowSimpleOrbitData(Vector3 apoapsisObject, Vector3 periapsisObject)
References SimpleKeplerOrbits.KeplerOrbitData.ApoapsisDistance, keplerOrbitMover, SimpleKeplerOrbits.KeplerOrbitMover.OrbitData, SimpleKeplerOrbits.KeplerOrbitData.PeriapsisDistance.
Referenced by Update.
void SimpleOrbitDataDisplay.ScaleTextWithScreen(float scaleAmount)
Referenced by LateUpdate.
void SimpleOrbitDataDisplay.FaceCamera()
Referenced by LateUpdate.