pb_Preferences
bool pb_Preferences.prefsLoaded
Referenced by PreferencesGUI.
Color pb_Preferences.pbDefaultFaceColor
Referenced by LoadPrefs, PreferencesGUI, SetPrefs.
Color pb_Preferences.pbDefaultEdgeColor
Referenced by LoadPrefs, PreferencesGUI, SetPrefs.
Color pb_Preferences.pbDefaultSelectedVertexColor
Referenced by LoadPrefs, PreferencesGUI, SetPrefs.
Color pb_Preferences.pbDefaultVertexColor
Referenced by LoadPrefs, PreferencesGUI, SetPrefs.
bool pb_Preferences.defaultOpenInDockableWindow
Referenced by LoadPrefs, PreferencesGUI, SetPrefs.
Material pb_Preferences.pbDefaultMaterial
Referenced by LoadPrefs, PreferencesGUI, SetPrefs.
Vector2 pb_Preferences.settingsScroll
Referenced by PreferencesGUI.
bool pb_Preferences.pbShowEditorNotifications
Referenced by LoadPrefs, PreferencesGUI, SetPrefs.
bool pb_Preferences.pbForceConvex
Referenced by LoadPrefs, PreferencesGUI, SetPrefs.
bool pb_Preferences.pbDragCheckLimit
Referenced by LoadPrefs, PreferencesGUI, SetPrefs.
bool pb_Preferences.pbForceVertexPivot
Referenced by LoadPrefs, PreferencesGUI, SetPrefs.
bool pb_Preferences.pbForceGridPivot
Referenced by LoadPrefs, PreferencesGUI, SetPrefs.
bool pb_Preferences.pbPerimeterEdgeBridgeOnly
Referenced by LoadPrefs, PreferencesGUI, SetPrefs.
bool pb_Preferences.pbPBOSelectionOnly
Referenced by LoadPrefs, PreferencesGUI, SetPrefs.
bool pb_Preferences.pbCloseShapeWindow
Referenced by LoadPrefs, PreferencesGUI, SetPrefs.
bool pb_Preferences.pbUVEditorFloating
Referenced by LoadPrefs, PreferencesGUI, SetPrefs.
bool pb_Preferences.pbStripProBuilderOnBuild
Referenced by LoadPrefs, PreferencesGUI, SetPrefs.
bool pb_Preferences.pbDisableAutoUV2Generation
Referenced by LoadPrefs, PreferencesGUI, SetPrefs.
bool pb_Preferences.pbShowSceneInfo
Referenced by LoadPrefs, PreferencesGUI, SetPrefs.
bool pb_Preferences.pbUniqueModeShortcuts
Referenced by LoadPrefs, PreferencesGUI, SetPrefs.
bool pb_Preferences.pbIconGUI
Referenced by LoadPrefs, PreferencesGUI, SetPrefs.
bool pb_Preferences.pbShiftOnlyTooltips
Referenced by LoadPrefs, PreferencesGUI, SetPrefs.
bool pb_Preferences.pbDrawAxisLines
Referenced by LoadPrefs, PreferencesGUI, SetPrefs.
bool pb_Preferences.pbMeshesAreAssets
Referenced by LoadPrefs, PreferencesGUI, SetPrefs.
bool pb_Preferences.pbElementSelectIsHamFisted
Referenced by LoadPrefs, PreferencesGUI, SetPrefs.
bool pb_Preferences.pbDragSelectWholeElement
Referenced by LoadPrefs, PreferencesGUI, SetPrefs.
bool pb_Preferences.pbEnableExperimental
Referenced by LoadPrefs, PreferencesGUI, SetPrefs.
bool pb_Preferences.showMissingLightmapUvWarning
Referenced by LoadPrefs, PreferencesGUI, SetPrefs.
ShadowCastingMode pb_Preferences.pbShadowCastingMode
Referenced by LoadPrefs, PreferencesGUI, SetPrefs.
ColliderType pb_Preferences.defaultColliderType
Referenced by LoadPrefs, PreferencesGUI, SetPrefs.
SceneToolbarLocation pb_Preferences.pbToolbarLocation
Referenced by LoadPrefs, PreferencesGUI, SetPrefs.
EntityType pb_Preferences.pbDefaultEntity
Referenced by LoadPrefs, PreferencesGUI, SetPrefs.
float pb_Preferences.pbUVGridSnapValue
Referenced by LoadPrefs, PreferencesGUI, SetPrefs.
float pb_Preferences.pbVertexHandleSize
Referenced by LoadPrefs, PreferencesGUI, SetPrefs.
pb_Shortcut [] pb_Preferences.defaultShortcuts
Referenced by LoadPrefs, SetPrefs, ShortcutEditPanel, ShortcutSelectPanel.
int pb_Preferences.shortcutIndex
Referenced by ShortcutEditPanel, ShortcutSelectPanel.
Rect pb_Preferences.selectBox
Referenced by ShortcutSelectPanel.
Rect pb_Preferences.shortcutEditRect
Referenced by ShortcutEditPanel.
Vector2 pb_Preferences.shortcutScroll
Referenced by ShortcutSelectPanel.
int pb_Preferences.CELL_HEIGHT
Referenced by ShortcutSelectPanel.
static void pb_Preferences.PreferencesGUI()
References defaultColliderType, defaultOpenInDockableWindow, LoadPrefs, pbCloseShapeWindow, pbDefaultEdgeColor, pbDefaultEntity, pbDefaultFaceColor, pbDefaultMaterial, pbDefaultSelectedVertexColor, pbDefaultVertexColor, pbDisableAutoUV2Generation, pbDragCheckLimit, pbDragSelectWholeElement, pbDrawAxisLines, pbElementSelectIsHamFisted, pbEnableExperimental, pbForceConvex, pbForceGridPivot, pbForceVertexPivot, pbIconGUI, pbMeshesAreAssets, pbPBOSelectionOnly, pbPerimeterEdgeBridgeOnly, pbShadowCastingMode, pbShiftOnlyTooltips, pbShowEditorNotifications, pbShowSceneInfo, pbStripProBuilderOnBuild, pbToolbarLocation, pbUniqueModeShortcuts, pbUVEditorFloating, pbUVGridSnapValue, pbVertexHandleSize, prefsLoaded, ResetToDefaults, SetPrefs, settingsScroll, ShortcutEditPanel, ShortcutSelectPanel, showMissingLightmapUvWarning.
static void pb_Preferences.ShortcutSelectPanel()
References CELL_HEIGHT, defaultShortcuts, selectBox, shortcutIndex, shortcutScroll.
Referenced by PreferencesGUI.
static void pb_Preferences.ShortcutEditPanel()
References defaultShortcuts, shortcutEditRect, shortcutIndex.
Referenced by PreferencesGUI.
static void pb_Preferences.LoadPrefs()
References defaultColliderType, defaultOpenInDockableWindow, defaultShortcuts, pbCloseShapeWindow, pbDefaultEdgeColor, pbDefaultEntity, pbDefaultFaceColor, pbDefaultMaterial, pbDefaultSelectedVertexColor, pbDefaultVertexColor, pbDisableAutoUV2Generation, pbDragCheckLimit, pbDragSelectWholeElement, pbDrawAxisLines, pbElementSelectIsHamFisted, pbEnableExperimental, pbForceConvex, pbForceGridPivot, pbForceVertexPivot, pbIconGUI, pbMeshesAreAssets, pbPBOSelectionOnly, pbPerimeterEdgeBridgeOnly, pbShadowCastingMode, pbShiftOnlyTooltips, pbShowEditorNotifications, pbShowSceneInfo, pbStripProBuilderOnBuild, pbToolbarLocation, pbUniqueModeShortcuts, pbUVEditorFloating, pbUVGridSnapValue, pbVertexHandleSize, showMissingLightmapUvWarning.
Referenced by PreferencesGUI, ResetToDefaults.
static void pb_Preferences.ResetToDefaults()
References LoadPrefs.
Referenced by PreferencesGUI.
static void pb_Preferences.SetPrefs()
References defaultColliderType, defaultOpenInDockableWindow, defaultShortcuts, pbCloseShapeWindow, pbDefaultEdgeColor, pbDefaultEntity, pbDefaultFaceColor, pbDefaultMaterial, pbDefaultSelectedVertexColor, pbDefaultVertexColor, pbDisableAutoUV2Generation, pbDragCheckLimit, pbDragSelectWholeElement, pbDrawAxisLines, pbElementSelectIsHamFisted, pbEnableExperimental, pbForceConvex, pbForceGridPivot, pbForceVertexPivot, pbIconGUI, pbMeshesAreAssets, pbPBOSelectionOnly, pbPerimeterEdgeBridgeOnly, pbShadowCastingMode, pbShiftOnlyTooltips, pbShowEditorNotifications, pbShowSceneInfo, pbStripProBuilderOnBuild, pbToolbarLocation, pbUniqueModeShortcuts, pbUVEditorFloating, pbUVGridSnapValue, pbVertexHandleSize, showMissingLightmapUvWarning.
Referenced by PreferencesGUI.