GetPlanetResources
bool GetPlanetResources.beginResouceTransfer
Referenced by OnTriggerEnter, OnTriggerExit, Update.
ResourcesDistribution GetPlanetResources.resourcesDistribution
Referenced by Start.
ShipData GetPlanetResources.shipData
Referenced by Start.
KeplerOrbitMover GetPlanetResources.keplerOrbitMover
Referenced by Start.
GameObject GetPlanetResources.currentOrbitingPlanet
Referenced by Start.
string GetPlanetResources.keyName
Referenced by OnTriggerEnter, Update.
void GetPlanetResources.Start()
References currentOrbitingPlanet, keplerOrbitMover, resourcesDistribution, shipData.
void GetPlanetResources.Update()
References beginResouceTransfer, GetResouceFromPlanet, keyName.
void GetPlanetResources.OnTriggerEnter(Collider other)
References beginResouceTransfer, keyName.
void GetPlanetResources.OnTriggerExit(Collider other)
References beginResouceTransfer.
IEnumerator GetPlanetResources.WaitTimeTillTransfer(float transferTimeFrame)
Referenced by GetResouceFromPlanet.
IEnumerator GetPlanetResources.ExtractResouces(PlanetResouces resoucesInstance, float transferSpeed)
Referenced by GetResouceFromPlanet.
void GetPlanetResources.GetResouceFromPlanet(string keyFromPair, float transferSpeed, float transferTimeFrame)
References ExtractResouces, PlanetResouces.IsEmpty, WaitTimeTillTransfer.
Referenced by Update.