Vectors
GameObject Vectors.velocityVector
Referenced by DrawVelocity, Start.
GameObject Vectors.headingVector
Referenced by DrawHeading, Start.
void Vectors.Start()
References headingVector, velocityVector.
void Vectors.Update()
References DrawHeading, DrawVelocity.
void Vectors.SetDrawPosition(LineRenderer gameojComponent, Vector3 position0, Vector3 position1)
Set position for drawing line using LineRenderer
Referenced by DrawHeading, DrawVelocity.
void Vectors.DrawVelocity()
References SetDrawPosition, velocityVector.
Referenced by Update.
void Vectors.DrawHeading()
References headingVector, SetDrawPosition.
Referenced by Update.