OrbitalManeuver
float OrbitalManeuver.debugLockEngine
float OrbitalManeuver.forceDampenent
float OrbitalManeuver.mobileFloatDampenent
Referenced by SetForceDampenent, SetNormalDown, SetNormalUp, SetPrograde, SetRadialIn, SetRadialOut, SetRetrograde.
GameObject OrbitalManeuver.velocityVector
Referenced by NormalManeuver, Update.
Vector3 OrbitalManeuver.mouseMoveDirection
Referenced by MouseInput.
OnGroundDetection OrbitalManeuver.onGroundDetection
Referenced by Start, Update.
ShipData OrbitalManeuver.shipData
Referenced by Start.
Vector3 OrbitalManeuver.mouseStartPos
Referenced by MouseInput.
Vector3 OrbitalManeuver.mouseEndpos
Referenced by MouseInput.
Vector2 OrbitalManeuver.touchStartPos
Referenced by TouchInput.
Vector2 OrbitalManeuver.touchEndPos
Referenced by TouchInput.
Vector3 OrbitalManeuver.prograde
Referenced by ProgradeManeuver, SetPrograde.
Vector3 OrbitalManeuver.retroGrade
Referenced by ProgradeManeuver.
Vector3 OrbitalManeuver.radialIn
Referenced by RadialManeuver, SetRadialIn.
Vector3 OrbitalManeuver.radialOut
Referenced by RadialManeuver, SetRadialOut.
Vector3 OrbitalManeuver.normalUp
Referenced by NormalManeuver, SetNormalUp.
Vector3 OrbitalManeuver.normalDown
Referenced by NormalManeuver, SetNormalDown.
Touch OrbitalManeuver.getTouch
Referenced by PointVelocityVectorToTarget, TouchInput.
VectorSnapUtils OrbitalManeuver.vectorSnapUtils
Referenced by ProgradeManeuver, RadialManeuver.
Vector3 OrbitalManeuver.TempTouchDirection
Vector3 OrbitalManeuver.TouchDirection
Referenced by NormalManeuver, ProgradeManeuver, RadialManeuver, TouchInput.
float OrbitalManeuver.VectorMagnitudeCap
Referenced by Awake, SpeedData.GetEnginePercentageInteger, SpeedData.GetEngineThrustPercentage, MouseInput, TouchInput.
float OrbitalManeuver.ForceStrength
Referenced by SpeedData.GetEnginePercentageInteger, SpeedData.GetEngineThrustPercentage, MouseInput, SetNormalDown, SetNormalUp, SetPrograde, SetRadialIn, SetRadialOut, SetRetrograde, TouchInput.
Vector3 OrbitalManeuver.Prograde
Vector3 OrbitalManeuver.RetroGrade
Vector3 OrbitalManeuver.RadialIn
Vector3 OrbitalManeuver.RadialOut
Vector3 OrbitalManeuver.NormalUp
Vector3 OrbitalManeuver.NormalDown
void OrbitalManeuver.Awake()
References GetScreenConstraint14, VectorMagnitudeCap.
void OrbitalManeuver.Start()
References onGroundDetection, shipData.
void OrbitalManeuver.Update()
References OnGroundDetection.isLanded, OnGroundDetection.liftOff, MouseInput, onGroundDetection, PointVelocityVectorToTarget, TouchInput, velocityVector.
void OrbitalManeuver.TouchInput()
References ForceStrength, getTouch, TouchDirection, touchEndPos, touchStartPos, VectorMagnitudeCap.
Referenced by Update.
void OrbitalManeuver.MouseInput()
References ForceStrength, mouseEndpos, mouseMoveDirection, mouseStartPos, VectorMagnitudeCap.
Referenced by Update.
bool OrbitalManeuver.RadialManeuver(GameObject velocityVector)
References VectorSnapUtils.CheckHorizontalSnap, radialIn, radialOut, SetRadialIn, SetRadialOut, TouchDirection, vectorSnapUtils.
bool OrbitalManeuver.NormalManeuver()
References normalDown, normalUp, SetNormalDown, SetNormalUp, TouchDirection, velocityVector.
bool OrbitalManeuver.ProgradeManeuver(GameObject velocityVector)
References VectorSnapUtils.CheckVerticalSnap, prograde, retroGrade, SetPrograde, SetRetrograde, TouchDirection, vectorSnapUtils.
void OrbitalManeuver.NeutralizeVelocityZAxis(GameObject velocityVector)
void OrbitalManeuver.PointVelocityVectorToTarget(GameObject velocityVector)
References GetScreenHalfpoint, getTouch.
Referenced by Update.
float OrbitalManeuver.GetScreenConstraint14(float width, float height)
Referenced by Awake.
Vector2 OrbitalManeuver.GetScreenHalfpoint(float width, float height)
Referenced by PointVelocityVectorToTarget.
void OrbitalManeuver.SetForceDampenent(float dampenent)
References mobileFloatDampenent.
Vector3 OrbitalManeuver.GetVelocityVectorPosition()
Vector3 OrbitalManeuver.SetPrograde(GameObject velocityVector, out Vector3 prograde)
References ForceStrength, mobileFloatDampenent, prograde.
Referenced by ProgradeManeuver.
Vector3 OrbitalManeuver.SetRetrograde(GameObject velocityVector, out Vector3 retrograde)
References ForceStrength, mobileFloatDampenent.
Referenced by ProgradeManeuver.
Vector3 OrbitalManeuver.SetRadialIn(GameObject velocityVector, out Vector3 radialIn)
References ForceStrength, mobileFloatDampenent, radialIn.
Referenced by RadialManeuver.
Vector3 OrbitalManeuver.SetRadialOut(GameObject velocityVector, out Vector3 radialOut)
References ForceStrength, mobileFloatDampenent, radialOut.
Referenced by RadialManeuver.
Vector3 OrbitalManeuver.SetNormalUp(GameObject velocityVector, out Vector3 normalUp)
References ForceStrength, mobileFloatDampenent, normalUp.
Referenced by NormalManeuver.
Vector3 OrbitalManeuver.SetNormalDown(GameObject velocityVector, out Vector3 normalDown)
References ForceStrength, mobileFloatDampenent, normalDown.
Referenced by NormalManeuver.