SimpleKeplerOrbits::KeplerOrbitMover
AttractorData SimpleKeplerOrbits.KeplerOrbitMover.AttractorSettings
The attractor settings data. Attractor object reference must be assigned or orbit mover will not work.
Referenced by SimpleKeplerOrbits.KeplerOrbitMover.ForceUpdateOrbitData, SimpleKeplerOrbits.KeplerOrbitMoverEditor.OnInspectorGUI, SimpleKeplerOrbits.KeplerOrbitMover.Update.
Transform SimpleKeplerOrbits.KeplerOrbitMover.VelocityHandle
The velocity handle object. Assign object and use it as velocity control handle in scene view.
Referenced by SimpleKeplerOrbits.KeplerOrbitMover.ForceUpdateOrbitData, SimpleKeplerOrbits.KeplerOrbitMover.ForceUpdateViewFromInternalState, SimpleKeplerOrbits.KeplerOrbitMover.OrbitUpdateLoop, SimpleKeplerOrbits.KeplerOrbitMover.SetAutoCircleOrbit, SimpleKeplerOrbits.KeplerOrbitMover.Update.
float SimpleKeplerOrbits.KeplerOrbitMover.TimeScale
The time scale multiplier.
Referenced by SimpleKeplerOrbits.KeplerOrbitMover.ForceUpdateOrbitData, SimpleKeplerOrbits.KeplerOrbitMover.OnApplicationQuit, SimpleKeplerOrbits.KeplerOrbitMover.OrbitUpdateLoop.
KeplerOrbitData SimpleKeplerOrbits.KeplerOrbitMover.OrbitData
The orbit data. Internal state of orbit.
Referenced by SimpleKeplerOrbits.KeplerOrbitMover.ForceUpdateOrbitData, SimpleKeplerOrbits.KeplerOrbitMover.ForceUpdateViewFromInternalState, SpeedData.GetAccelerationStringData, SimpleKeplerOrbits.KeplerOrbitMover.OnApplicationQuit, SimpleKeplerOrbits.KeplerOrbitMoverEditor.OnInspectorGUI, SimpleKeplerOrbits.KeplerOrbitMover.OrbitUpdateLoop, SimpleKeplerOrbits.KeplerOrbitMover.SetAutoCircleOrbit, SimpleOrbitDataDisplay.ShowSimpleOrbitData, SimpleOrbitDataDisplay.Update, SimpleKeplerOrbits.KeplerOrbitMover.Update.
bool SimpleKeplerOrbits.KeplerOrbitMover.LockOrbitEditing
Disable continious editing orbit in update loop, if you don't need it.
Referenced by SimpleKeplerOrbits.KeplerOrbitMover.Update.
bool SimpleKeplerOrbits.KeplerOrbitMover.isNotPlanet
Referenced by SimpleKeplerOrbits.KeplerOrbitMover.ForceUpdateOrbitData, SimpleKeplerOrbits.KeplerOrbitMover.OnApplicationQuit, SimpleKeplerOrbits.KeplerOrbitMover.OnEnable, SimpleKeplerOrbits.KeplerOrbitMover.OrbitUpdateLoop.
bool SimpleKeplerOrbits.KeplerOrbitMover.isStaticInstance
Referenced by SimpleKeplerOrbits.KeplerOrbitMover.OnEnable.
bool SimpleKeplerOrbits.KeplerOrbitMover.initializeLoadData
Referenced by SimpleKeplerOrbits.KeplerOrbitMover.ForceUpdateOrbitData.
OrbitalManeuver SimpleKeplerOrbits.KeplerOrbitMover.orbitalManeuver
Referenced by SimpleKeplerOrbits.KeplerOrbitMover.OnEnable.
string SimpleKeplerOrbits.KeplerOrbitMover.attractorObjectName
Referenced by SimpleKeplerOrbits.KeplerOrbitMover.OnApplicationQuit, SimpleKeplerOrbits.KeplerOrbitMover.Start.
string SimpleKeplerOrbits.KeplerOrbitMover.velocityHandleName
bool SimpleKeplerOrbits.KeplerOrbitMover.IsReferencesAsigned
Referenced by SimpleKeplerOrbits.KeplerOrbitMover.CreateNewOrbitFromPositionAndVelocity, SimpleKeplerOrbits.KeplerOrbitMover.ForceUpdateOrbitData, SimpleKeplerOrbits.KeplerOrbitMover.OrbitUpdateLoop, SimpleKeplerOrbits.KeplerOrbitMover.SetAutoCircleOrbit, SimpleKeplerOrbits.KeplerOrbitMover.Update.
void SimpleKeplerOrbits.KeplerOrbitMover.OnApplicationQuit()
References SimpleKeplerOrbits.KeplerOrbitMover.attractorObjectName, SimpleKeplerOrbits.KeplerOrbitMover.isNotPlanet, SimpleKeplerOrbits.KeplerOrbitMover.OrbitData, SimpleKeplerOrbits.KeplerOrbitMover.TimeScale.
void SimpleKeplerOrbits.KeplerOrbitMover.OnEnable()
References SimpleKeplerOrbits.KeplerOrbitMover.isNotPlanet, SimpleKeplerOrbits.KeplerOrbitMover.isStaticInstance, SimpleKeplerOrbits.KeplerOrbitMover.orbitalManeuver, SimpleKeplerOrbits.KeplerOrbitMover.OrbitUpdateLoop.
void SimpleKeplerOrbits.KeplerOrbitMover.Start()
References SimpleKeplerOrbits.KeplerOrbitMover.attractorObjectName.
void SimpleKeplerOrbits.KeplerOrbitMover.Update()
Updates orbit internal data.
In this method orbit data is updating from view state: If you change body position, attractor mass or any other vital orbit parameter, this change will be noticed and applyed to internal OrbitData state in this method. If you need to change orbitData state directly, by script, you need to change OrbitData state and then call ForceUpdateOrbitData
References SimpleKeplerOrbits.AttractorData.AttractorMass, SimpleKeplerOrbits.KeplerOrbitData.AttractorMass, SimpleKeplerOrbits.AttractorData.AttractorObject, SimpleKeplerOrbits.KeplerOrbitMover.AttractorSettings, SimpleKeplerOrbits.KeplerOrbitMover.ForceUpdateOrbitData, SimpleKeplerOrbits.KeplerOrbitData.GravConst, SimpleKeplerOrbits.AttractorData.GravityConstant, SimpleKeplerOrbits.KeplerOrbitMover.IsReferencesAsigned, SimpleKeplerOrbits.KeplerOrbitMover.LockOrbitEditing, SimpleKeplerOrbits.KeplerOrbitMover.OrbitData, SimpleKeplerOrbits.KeplerOrbitData.Position, SimpleKeplerOrbits.KeplerOrbitData.Velocity, SimpleKeplerOrbits.KeplerOrbitMover.VelocityHandle.
IEnumerator SimpleKeplerOrbits.KeplerOrbitMover.OrbitUpdateLoop()
Progress orbit path motion. Actual kepler orbiting is processed here.
Orbit motion progress calculations must be placed after Update, so orbit parameters changes can be applyed, but before LateUpdate, so orbit can be displayed in same frame. Coroutine loop is best candidate for achieving this.
References SimpleKeplerOrbits.KeplerOrbitMover.isNotPlanet, SimpleKeplerOrbits.KeplerOrbitMover.IsReferencesAsigned, SimpleKeplerOrbits.KeplerOrbitData.IsValidOrbit, SimpleKeplerOrbits.KeplerOrbitMover.OrbitData, SimpleKeplerOrbits.KeplerOrbitData.Position, SimpleKeplerOrbits.KeplerOrbitMover.TimeScale, SimpleKeplerOrbits.KeplerOrbitData.Velocity, SimpleKeplerOrbits.KeplerOrbitMover.VelocityHandle.
Referenced by SimpleKeplerOrbits.KeplerOrbitMover.OnEnable.
void SimpleKeplerOrbits.KeplerOrbitMover.CreateNewOrbitFromPositionAndVelocity(Vector3 relativePosition, Vector3 velocity)
Updates OrbitData from new body position and velocity vectors.
relativePosition The relative position. velocity The relative velocity. This method can be useful to assign new position of body by script. Or you can directly change OrbitData state and then manually update view.
References SimpleKeplerOrbits.KeplerOrbitMover.ForceUpdateViewFromInternalState, SimpleKeplerOrbits.KeplerOrbitMover.IsReferencesAsigned.
void SimpleKeplerOrbits.KeplerOrbitMover.ForceUpdateViewFromInternalState()
Forces the update of body position, and velocity handler from OrbitData. Call this method after any direct changing of OrbitData.
References SimpleKeplerOrbits.KeplerOrbitMover.OrbitData, SimpleKeplerOrbits.KeplerOrbitData.Position, SimpleKeplerOrbits.KeplerOrbitData.Velocity, SimpleKeplerOrbits.KeplerOrbitMover.VelocityHandle.
Referenced by SimpleKeplerOrbits.KeplerOrbitMover.CreateNewOrbitFromPositionAndVelocity.
void SimpleKeplerOrbits.KeplerOrbitMover.ForceUpdateOrbitData()
Forces the update of internal orbit data from current world positions of body, attractor settings and velocityHandle.
This method must be called after any manual changing of body position, velocity handler position or attractor settings. It will update internal OrbitData state from view state.
References SimpleKeplerOrbits.AttractorData.AttractorObject, SimpleKeplerOrbits.KeplerOrbitMover.AttractorSettings, SimpleKeplerOrbits.KeplerOrbitMover.initializeLoadData, SimpleKeplerOrbits.KeplerOrbitMover.isNotPlanet, SimpleKeplerOrbits.KeplerOrbitMover.IsReferencesAsigned, SimpleKeplerOrbits.KeplerOrbitMover.OrbitData, SaveState.OrbitalData.SavedDataDictionary, SimpleKeplerOrbits.KeplerOrbitMover.TimeScale, SimpleKeplerOrbits.KeplerOrbitMover.VelocityHandle.
Referenced by SimpleKeplerOrbits.KeplerOrbitMover.Update.
void SimpleKeplerOrbits.KeplerOrbitMover.SetAutoCircleOrbit()
Change orbit velocity vector to match circular orbit.
References SimpleKeplerOrbits.KeplerOrbitMover.IsReferencesAsigned, SimpleKeplerOrbits.KeplerOrbitMover.OrbitData, SimpleKeplerOrbits.KeplerOrbitData.Velocity, SimpleKeplerOrbits.KeplerOrbitMover.VelocityHandle.