LibNoise::Noise2D
readonly double LibNoise.Noise2D.South
readonly double LibNoise.Noise2D.North
readonly double LibNoise.Noise2D.West
readonly double LibNoise.Noise2D.East
readonly double LibNoise.Noise2D.AngleMin
readonly double LibNoise.Noise2D.AngleMax
readonly double LibNoise.Noise2D.Left
readonly double LibNoise.Noise2D.Right
readonly double LibNoise.Noise2D.Top
readonly double LibNoise.Noise2D.Bottom
int LibNoise.Noise2D._width
Referenced by LibNoise.Noise2D.Clear, LibNoise.Noise2D.Disposing, LibNoise.Noise2D.GenerateCylindrical, LibNoise.Noise2D.GeneratePlanar, LibNoise.Noise2D.GenerateSpherical, LibNoise.Noise2D.GetData, LibNoise.Noise2D.GetNormalMap, LibNoise.Noise2D.GetTexture, LibNoise.Noise2D.Noise2D.
int LibNoise.Noise2D._height
Referenced by LibNoise.Noise2D.Clear, LibNoise.Noise2D.Disposing, LibNoise.Noise2D.GenerateCylindrical, LibNoise.Noise2D.GeneratePlanar, LibNoise.Noise2D.GenerateSpherical, LibNoise.Noise2D.GetData, LibNoise.Noise2D.GetNormalMap, LibNoise.Noise2D.GetTexture, LibNoise.Noise2D.Noise2D.
float [,] LibNoise.Noise2D._data
Referenced by LibNoise.Noise2D.Clear, LibNoise.Noise2D.Disposing, LibNoise.Noise2D.GenerateCylindrical, LibNoise.Noise2D.GeneratePlanar, LibNoise.Noise2D.GenerateSpherical, LibNoise.Noise2D.GetData, LibNoise.Noise2D.GetTexture, LibNoise.Noise2D.Noise2D.
readonly int LibNoise.Noise2D._ucWidth
Referenced by LibNoise.Noise2D.GenerateCylindrical, LibNoise.Noise2D.GeneratePlanar, LibNoise.Noise2D.GenerateSpherical, LibNoise.Noise2D.GetData, LibNoise.Noise2D.GetNormalMap, LibNoise.Noise2D.Noise2D.
readonly int LibNoise.Noise2D._ucHeight
Referenced by LibNoise.Noise2D.GenerateCylindrical, LibNoise.Noise2D.GeneratePlanar, LibNoise.Noise2D.GenerateSpherical, LibNoise.Noise2D.GetData, LibNoise.Noise2D.GetNormalMap, LibNoise.Noise2D.Noise2D.
int LibNoise.Noise2D._ucBorder
Referenced by LibNoise.Noise2D.GenerateCylindrical, LibNoise.Noise2D.GeneratePlanar, LibNoise.Noise2D.GenerateSpherical, LibNoise.Noise2D.GetNormalMap, LibNoise.Noise2D.GetTexture, LibNoise.Noise2D.Noise2D.
readonly float [,] LibNoise.Noise2D._ucData
Referenced by LibNoise.Noise2D.GenerateCylindrical, LibNoise.Noise2D.GeneratePlanar, LibNoise.Noise2D.GenerateSpherical, LibNoise.Noise2D.GetData, LibNoise.Noise2D.GetNormalMap, LibNoise.Noise2D.Noise2D.
float LibNoise.Noise2D._borderValue
Referenced by LibNoise.Noise2D.GetTexture.
ModuleBase LibNoise.Noise2D._generator
Referenced by LibNoise.Noise2D.GenerateCylindrical, LibNoise.Noise2D.GeneratePlanar, LibNoise.Noise2D.GenerateSpherical, LibNoise.Noise2D.Noise2D.
bool LibNoise.Noise2D._disposed
Referenced by LibNoise.Noise2D.Dispose.
float LibNoise.Noise2D.this[int x, int y, bool isCropped=true]
Gets or sets a value in the noise map by its position.
x The position on the x-axis. y The position on the y-axis. isCropped Indicates whether to select the cropped (default) or uncropped noise map data. The corresponding value.
float LibNoise.Noise2D.Border
Gets or sets the constant value at the noise maps borders.
ModuleBase LibNoise.Noise2D.Generator
Gets or sets the generator module.
int LibNoise.Noise2D.Height
Gets the height of the noise map.
int LibNoise.Noise2D.Width
Gets the width of the noise map.
bool LibNoise.Noise2D.IsDisposed
Gets a value whether the object is disposed.
LibNoise.Noise2D.Noise2D()
Initializes a new instance of Noise2D.
virtual bool LibNoise.Noise2D.Disposing()
Immediately releases the unmanaged resources used by this object.
True if the object is completely disposed.
References LibNoise.Noise2D._data, LibNoise.Noise2D._height, LibNoise.Noise2D._width.
Referenced by LibNoise.Noise2D.Dispose.
LibNoise.Noise2D.Noise2D(int size)
Initializes a new instance of Noise2D.
size The width and height of the noise map.
LibNoise.Noise2D.Noise2D(int size, ModuleBase generator)
Initializes a new instance of Noise2D.
size The width and height of the noise map. generator The generator module.
LibNoise.Noise2D.Noise2D(int width, int height, ModuleBase generator=null)
Initializes a new instance of Noise2D.
width The width of the noise map. height The height of the noise map. generator The generator module.
References LibNoise.Noise2D._data, LibNoise.Noise2D._generator, LibNoise.Noise2D._height, LibNoise.Noise2D._ucBorder, LibNoise.Noise2D._ucData, LibNoise.Noise2D._ucHeight, LibNoise.Noise2D._ucWidth, LibNoise.Noise2D._width.
float [,] LibNoise.Noise2D.GetNormalizedData(bool isCropped=true, int xCrop=0, int yCrop=0)
Gets normalized noise map data with all values in the set of {0..1}.
isCropped Indicates whether to select the cropped (default) or uncropped noise map data. xCrop This value crops off data from the right of the noise map data. yCrop This value crops off data from the bottom of the noise map data. The normalized noise map data.
References LibNoise.Noise2D.GetData.
float [,] LibNoise.Noise2D.GetData(bool isCropped=true, int xCrop=0, int yCrop=0, bool isNormalized=false)
Gets noise map data.
isCropped Indicates whether to select the cropped (default) or uncropped noise map data. xCrop This value crops off data from the right of the noise map data. yCrop This value crops off data from the bottom of the noise map data. isNormalized Indicates whether to normalize noise map data. The noise map data.
References LibNoise.Noise2D._data, LibNoise.Noise2D._height, LibNoise.Noise2D._ucData, LibNoise.Noise2D._ucHeight, LibNoise.Noise2D._ucWidth, LibNoise.Noise2D._width.
Referenced by LibNoise.Noise2D.GetNormalizedData.
void LibNoise.Noise2D.Clear(float value=0f)
Clears the noise map.
value The constant value to clear the noise map with.
References LibNoise.Noise2D._data, LibNoise.Noise2D._height, LibNoise.Noise2D._width.
void LibNoise.Noise2D.GeneratePlanar(double left, double right, double top, double bottom, bool isSeamless=true)
Generates a non-seamless planar projection of the noise map.
left The clip region to the left. right The clip region to the right. top The clip region to the top. bottom The clip region to the bottom. isSeamless Indicates whether the resulting noise map should be seamless.
References LibNoise.Noise2D._data, LibNoise.Noise2D._generator, LibNoise.Noise2D._height, LibNoise.Noise2D._ucBorder, LibNoise.Noise2D._ucData, LibNoise.Noise2D._ucHeight, LibNoise.Noise2D._ucWidth, LibNoise.Noise2D._width, LibNoise.Noise2D.GeneratePlanar, LibNoise.Utils.InterpolateLinear.
void LibNoise.Noise2D.GenerateCylindrical(double angleMin, double angleMax, double heightMin, double heightMax)
Generates a cylindrical projection of the noise map.
angleMin The maximum angle of the clip region. angleMax The minimum angle of the clip region. heightMin The minimum height of the clip region. heightMax The maximum height of the clip region.
References LibNoise.Noise2D._data, LibNoise.Noise2D._generator, LibNoise.Noise2D._height, LibNoise.Noise2D._ucBorder, LibNoise.Noise2D._ucData, LibNoise.Noise2D._ucHeight, LibNoise.Noise2D._ucWidth, LibNoise.Noise2D._width, LibNoise.Noise2D.GenerateCylindrical.
void LibNoise.Noise2D.GenerateSpherical(double south, double north, double west, double east)
Generates a spherical projection of the noise map.
south The clip region to the south. north The clip region to the north. west The clip region to the west. east The clip region to the east.
References LibNoise.Noise2D._data, LibNoise.Noise2D._generator, LibNoise.Noise2D._height, LibNoise.Noise2D._ucBorder, LibNoise.Noise2D._ucData, LibNoise.Noise2D._ucHeight, LibNoise.Noise2D._ucWidth, LibNoise.Noise2D._width, LibNoise.Noise2D.GenerateSpherical.
Texture2D LibNoise.Noise2D.GetTexture()
Creates a grayscale texture map for the current content of the noise map.
The created texture map.
References LibNoise.GradientPresets.Grayscale.
Texture2D LibNoise.Noise2D.GetTexture(Gradient gradient)
Creates a texture map for the current content of the noise map.
gradient The gradient to color the texture map with. The created texture map.
References LibNoise.Noise2D._borderValue, LibNoise.Noise2D._data, LibNoise.Noise2D._height, LibNoise.Noise2D._ucBorder, LibNoise.Noise2D._width.
Texture2D LibNoise.Noise2D.GetNormalMap(float intensity)
Creates a normal map for the current content of the noise map.
intensity The scaling of the normal map values. The created normal map.
References LibNoise.Noise2D._height, LibNoise.Noise2D._ucBorder, LibNoise.Noise2D._ucData, LibNoise.Noise2D._ucHeight, LibNoise.Noise2D._ucWidth, LibNoise.Noise2D._width.
void LibNoise.Noise2D.Dispose()
Immediately releases the unmanaged resources used by this object.
References LibNoise.Noise2D._disposed, LibNoise.Noise2D.Disposing.
double LibNoise.Noise2D.GeneratePlanar(double x, double y)
Generates a planar projection of a point in the noise map.
x The position on the x-axis. y The position on the y-axis. The corresponding noise map value.
Referenced by LibNoise.Noise2D.GeneratePlanar.
double LibNoise.Noise2D.GenerateCylindrical(double angle, double height)
Generates a cylindrical projection of a point in the noise map.
angle The angle of the point. height The height of the point. The corresponding noise map value.
Referenced by LibNoise.Noise2D.GenerateCylindrical.
double LibNoise.Noise2D.GenerateSpherical(double lat, double lon)
Generates a spherical projection of a point in the noise map.
lat The latitude of the point. lon The longitude of the point. The corresponding noise map value.
Referenced by LibNoise.Noise2D.GenerateSpherical.