UITouchManager
GameObject UITouchManager.mainUI
GameObject [] UITouchManager.uiControls
Referenced by ActivateUIOptions, DeactiavateInactiveUI, DeactivateAllUI, DeactivateOtherUI.
GameObject UITouchManager.cancelUI
bool UITouchManager.displayUIOptions
bool UITouchManager.cancelBool
Queue<bool> UITouchManager.activationMessageQueue
Referenced by Update.
List<GameObject> UITouchManager.activeUI
Referenced by ActivateUIOptions, DeactiavateInactiveUI, DeactivateOtherUI, Update.
GameObject UITouchManager.currentUI
CameraMovement UITouchManager.cameraMovement
Referenced by Start.
Vector3 UITouchManager.firstTouchPos
Vector3 UITouchManager.secondTouchPos
bool UITouchManager.isTouchZone
Vector3 UITouchManager.mouseStartPos
Vector3 UITouchManager.mouseEndpos
Vector3 UITouchManager.mouseMoveDirection
bool UITouchManager.CancelBool
Referenced by Update.
bool UITouchManager.DisplayUIOptions
Queue<bool> UITouchManager.ActivationMessageQueue
Referenced by Update.
void UITouchManager.Start()
References cameraMovement.
void UITouchManager.Update()
References ActivateUIOptions, activationMessageQueue, ActivationMessageQueue, activeUI, CancelBool, DeactiavateInactiveUI, DeactivateAllUI, MoveUIWithPlayer.
void UITouchManager.MoveUIWithPlayer()
Referenced by Update.
void UITouchManager.RestartTouchUI()
Referenced by DeactivateOtherUI.
void UITouchManager.ActivateUIOptions()
References activeUI, uiControls.
Referenced by Update.
void UITouchManager.DeactivateAllUI()
References uiControls.
Referenced by Update.
void UITouchManager.DeactiavateInactiveUI()
References activeUI, uiControls.
Referenced by Update.
void UITouchManager.DeactivateOtherUI(GameObject thisUI)
References activeUI, RestartTouchUI, uiControls.
void UITouchManager.RemoveFromActiveUIList(GameObject thisUI)