PlayerUIDetection
float PlayerUIDetection.colliderScaleAmount
Referenced by ScaleColliderWithScreen.
UITouchManager PlayerUIDetection.uiTouchManager
Referenced by Start.
OrbitalManeuver PlayerUIDetection.orbitalManeuver
Referenced by Start.
CameraMovement PlayerUIDetection.cameraMovement
Referenced by SendActivateSignal, Start.
const int PlayerUIDetection._playerSelectionLayer
Referenced by Update.
GameObject PlayerUIDetection.maneuverBubble
Referenced by Start.
InputDetectionUtils PlayerUIDetection.inputDetectionUtils
Referenced by RayCastToCollider, Update.
void PlayerUIDetection.Start()
References cameraMovement, maneuverBubble, orbitalManeuver, uiTouchManager.
void PlayerUIDetection.Update()
References _playerSelectionLayer, inputDetectionUtils, InputDetectionUtils.ProcessTouchStateOnePoint, RayCastToCollider, ScaleColliderWithScreen.
void PlayerUIDetection.SendActivateSignal()
References cameraMovement, EnableManeuverBubbleFx, CameraMovement.IsMoving.
Referenced by RayCastToCollider.
void PlayerUIDetection.ScaleColliderWithScreen(float scaleFactor)
References colliderScaleAmount.
Referenced by Update.
void PlayerUIDetection.RayCastToCollider(int layerIntIndex)
References inputDetectionUtils, SendActivateSignal, SetFocusExitConditions, InputDetectionUtils.TouchStartPos.
Referenced by Update.
void PlayerUIDetection.SetFocusExitConditions()
References DeactivateManeuverBubbleFx.
Referenced by RayCastToCollider.
void PlayerUIDetection.EnableManeuverBubbleFx()
Referenced by SendActivateSignal.
void PlayerUIDetection.DeactivateManeuverBubbleFx()
Referenced by SetFocusExitConditions.