CameraMovement
GameObject CameraMovement.player
bool CameraMovement.swtichTargetBool
float CameraMovement.zoomDistanceAuto
float CameraMovement.zoomDistanceFixed
float CameraMovement.uiFocusDistance
float CameraMovement.uiFocusZoomSpeed
float CameraMovement.lockZoomAtSize
float CameraMovement.touchZoomSpeed
Referenced by PinchZoom.
float CameraMovement.dragDampenent3D
Referenced by RotateCameraAroundCurrentObject, RotateCameraAroundPlanetAxis.
float CameraMovement.debug3DRotationSpeed
Referenced by Camera3DMovement, RotateCameraAroundPlanetAxis.
GameObject CameraMovement.debugCurrentCam
bool CameraMovement.IsFocusRequested
Referenced by FocusToNewTarget, LateUpdate.
GameObject CameraMovement.CurrentCameraObject
Referenced by FocusToNewTarget, LateUpdate, PinchZoom, Start.
bool CameraMovement.EnableCamMovement
Referenced by Start.
bool CameraMovement.IsMoving
Referenced by LateUpdate, PlanetSelectionUI.OnTouchStay, PinchZoom, PlayerUIDetection.SendActivateSignal.
bool CameraMovement.UiGainControl
Referenced by LateUpdate.
bool CameraMovement.EnableAutoZoom
Referenced by DebugUI.AutoZoom, LateUpdate.
KeplerOrbitMover CameraMovement.keplerOrbitMover
float CameraMovement.oldCamSize
float CameraMovement.spinAngle
Transform CameraMovement.cameraRotationalAxis
Referenced by SetCameraRotationalAxis.
float CameraMovement.rotationalStep
InputDetectionUtils CameraMovement.inputDetectionUtils
Referenced by Camera3DMovement, ProcessTilting, Update.
void CameraMovement.Start()
References CurrentCameraObject, EnableCamMovement.
void CameraMovement.Update()
References Camera3DMovement, inputDetectionUtils, ProcessTilting, InputDetectionUtils.TouchStartPos.
void CameraMovement.LateUpdate()
References CurrentCameraObject, EnableAutoZoom, FocusToNewTarget, IsFocusRequested, IsMoving, UiGainControl, ZoomEffect.
Vector3 CameraMovement.GetCenterTargetPosition(Transform target)
Referenced by FocusToNewTarget, LockOnToTarget.
void CameraMovement.ZoomEffect(bool isAutoZoom, bool uiGainControl)
References PinchZoom.
Referenced by LateUpdate.
void CameraMovement.PinchZoom()
References CurrentCameraObject, IsMoving, touchZoomSpeed.
Referenced by ZoomEffect.
void CameraMovement.Camera3DMovement()
References debug3DRotationSpeed, InputDetectionUtils.ForceStrength, inputDetectionUtils, InputDetectionUtils.MoveDirection, RotateCameraAroundCurrentObject, RotateCameraAroundPlanetAxis, InputDetectionUtils.TouchCount.
Referenced by Update.
IEnumerator CameraMovement.RotateCameraAroundPlanetAxis(string direction, float touchDragDistance)
References debug3DRotationSpeed, dragDampenent3D, FocusToNewTarget.
Referenced by Camera3DMovement.
void CameraMovement.RotateCameraAroundCurrentObject(string direction, float touchDragDistance)
References dragDampenent3D.
Referenced by Camera3DMovement.
Vector3 CameraMovement.SetLerpPosition(Transform target, float lerpTime)
Referenced by FocusToNewTarget.
IEnumerator CameraMovement.LookAtTarget(Transform target, float rotationalSpeed)
Referenced by FocusToNewTarget.
void CameraMovement.LockOnToTarget(Transform target)
References GetCenterTargetPosition.
void CameraMovement.SetCameraRotationalAxis(Transform target)
References cameraRotationalAxis.
string CameraMovement.TiltDirection(Vector2 touch0, Vector2 touch1)
void CameraMovement.ProcessTilting(Vector2 touch0)
References InputDetectionUtils.Begin, inputDetectionUtils, InputDetectionUtils.Moving, InputDetectionUtils.ProcessTouchStateOnePoint, InputDetectionUtils.TouchStartPos.
Referenced by Update.
void CameraMovement.FocusToNewTarget(Transform target, float lerpTime)
References CurrentCameraObject, GetCenterTargetPosition, IsFocusRequested, LookAtTarget, SetLerpPosition.
Referenced by LateUpdate, RotateCameraAroundPlanetAxis.