CubeFace
CubeFace CubeFace.parent
Referenced by CubePlanet.CubePlanet, Generate, Initialize.
CubeFace [] CubeFace.tree
Referenced by CubePlanet.GetActiveQuadTreeFaces, Merge, SubDivide.
bool [] CubeFace.neighbours
Referenced by CubePlanet.ProcessNeighbours.
bool CubeFace.generated
Referenced by Dispose, Generate.
bool CubeFace.finalized
Referenced by CubePlanet.FinalizeFace.
bool CubeFace.textured
Referenced by Texturize.
Material CubeFace.material
Referenced by Initialize, Texturize.
Mesh CubeFace.mesh
Referenced by Generate, CubePlanet.ProcessNeighbours, Texturize.
MeshFilter CubeFace.filter
Referenced by Initialize.
MeshRenderer CubeFace.renderer
Referenced by Initialize.
MeshCollider CubeFace.collider
Referenced by Initialize.
GameObject CubeFace.gameObject
Referenced by Initialize.
int CubeFace.size
Referenced by Generate, Initialize, SubDivide, Texturize.
float CubeFace.scale
Referenced by Generate, Initialize, CubePlanet.ProcessNeighbours, SubDivide.
Vector3 CubeFace.position
Referenced by Generate, Initialize, SubDivide.
Vector3 CubeFace.left
Referenced by Generate, Initialize, SubDivide.
Vector3 CubeFace.forward
Referenced by Generate, Initialize, SubDivide.
CubeFace.CubeFace(CubeFace parent, Vector3 pos, Vector3 left, Vector3 forward, float scale, int size)
Initialize a sub-Cubeface with a parent referece.
References Initialize.
Referenced by SubDivide.
CubeFace.CubeFace(Vector3 pos, Vector3 left, Vector3 forward, float scale, int size)
References Initialize.
void CubeFace.Generate()
Used to first generate the plane's verts, uvs and tris If already generated, turns on this CubeFace's renderer and collider (makes it active on the planet)
References forward, generated, left, mesh, parent, position, scale, size.
Referenced by Initialize.
void CubeFace.Texturize()
Must be called after mesh.RecalculateNormals (needs normal values) Generates normal map and applies grayscale texture to CubeFace's material
References material, mesh, size, textured.
void CubeFace.Merge()
Quadtree merge of any children
References tree.
void CubeFace.Dispose()
References generated.
Referenced by SubDivide.
void CubeFace.SubDivide()
Quadtree subdivide Creates 4 sub-CubeFaces taking same space as current mesh, doubling the detail.
References CubeFace, Dispose, forward, left, position, scale, size, tree.
void CubeFace.Initialize(CubeFace parent, Vector3 pos, Vector3 left, Vector3 forward, float scale, int size)
Creates a CubeFace
parent Associated parent reference as a QuadTree sibling pos Position vector to render the cubeface at left The x axis of the plane forward The z axis of the plane scale The scale of the plane size The number of vertices in length/width to create (segments)
References collider, filter, forward, gameObject, Generate, left, material, parent, position, renderer, scale, size.
Referenced by CubeFace.