VectorSnapUtils
float VectorSnapUtils.GetAngleToCompareVector(Vector3 targetDirectionVector, Vector3 compareVector)
float VectorSnapUtils.GetAngleToVectorRight(Vector3 targetDirectionVector)
Referenced by CheckHorizontalSnap, CheckVerticalSnap.
float VectorSnapUtils.GetAngleToVectorUp(Vector3 targetDirectionVector)
Referenced by CheckHorizontalSnap, CheckVerticalSnap.
bool VectorSnapUtils.CheckHorizontalSnap(Vector3 direction)
References GetAngleToVectorRight, GetAngleToVectorUp.
Referenced by OrbitalManeuver.RadialManeuver.
bool VectorSnapUtils.CheckVerticalSnap(Vector3 direction)
References GetAngleToVectorRight, GetAngleToVectorUp.
Referenced by OrbitalManeuver.ProgradeManeuver.
bool VectorSnapUtils.CheckSkewedSnap(Vector3 direction)