EditorCallbackViewer
List<string> EditorCallbackViewer.logs
Referenced by OnGUI.
Vector2 EditorCallbackViewer.scroll
Referenced by OnGUI.
bool EditorCallbackViewer.collapse
Referenced by OnGUI.
Color EditorCallbackViewer.logBackgroundColor
Referenced by OnGUI.
Color EditorCallbackViewer.disabledColor
Referenced by OnGUI.
static void EditorCallbackViewer.MenuInitEditorCallbackViewer()
void EditorCallbackViewer.OnEnable()
References OnEditLevelChanged, OnMeshCompiled, OnProBuilderObjectCreated, OnSelectionUpdate, OnVertexMovementBegin, OnVertexMovementFinish.
void EditorCallbackViewer.OnDisable()
References OnEditLevelChanged, OnMeshCompiled, OnProBuilderObjectCreated, OnSelectionUpdate, OnVertexMovementBegin, OnVertexMovementFinish.
void EditorCallbackViewer.OnProBuilderObjectCreated(pb_Object pb)
References AddLog.
Referenced by OnDisable, OnEnable.
void EditorCallbackViewer.OnEditLevelChanged(int editLevel)
References AddLog.
Referenced by OnDisable, OnEnable.
void EditorCallbackViewer.OnSelectionUpdate(pb_Object[] selection)
References AddLog.
Referenced by OnDisable, OnEnable.
void EditorCallbackViewer.OnVertexMovementBegin(pb_Object[] selection)
References AddLog.
Referenced by OnDisable, OnEnable.
void EditorCallbackViewer.OnVertexMovementFinish(pb_Object[] selection)
References AddLog.
Referenced by OnDisable, OnEnable.
void EditorCallbackViewer.OnMeshCompiled(pb_Object pb, Mesh mesh)
References AddLog.
Referenced by OnDisable, OnEnable.
void EditorCallbackViewer.AddLog(string summary)
Referenced by OnEditLevelChanged, OnMeshCompiled, OnProBuilderObjectCreated, OnSelectionUpdate, OnVertexMovementBegin, OnVertexMovementFinish.
void EditorCallbackViewer.OnGUI()
References collapse, disabledColor, logBackgroundColor, logs, scroll.