OrbitalManeuverV2
GameObject OrbitalManeuverV2.player
Referenced by EngineBurn, Start.
bool OrbitalManeuverV2.isOutOfBound
InputDetectionUtils OrbitalManeuverV2.inputDetectionUtils
Referenced by EngineBurn, MoveVelVectorTowardsDesinatedPos, SetRotationalMatrix, Update.
ScreenUtils OrbitalManeuverV2.screenUtils
RotationMatrixHelper OrbitalManeuverV2.rotationMatrixHelper
Referenced by MoveVelVectorTowardsDesinatedPos.
double [] OrbitalManeuverV2.points
Referenced by MoveVelVectorTowardsDesinatedPos.
Vector3 OrbitalManeuverV2.rotatedPoint
Referenced by MoveVelVectorTowardsDesinatedPos.
Vector3 OrbitalManeuverV2.axisOfRotation
Referenced by DebugKeyboardInput, Update.
float OrbitalManeuverV2.rotationalSpeed
Referenced by SetRotationalMatrix, SetRotationalSpeed.
float OrbitalManeuverV2.boundingBoxFloatConst
GameObject OrbitalManeuverV2.boundingBoxGameobject
float OrbitalManeuverV2.rotationalSpeedDampenent
Referenced by SetRotationalMatrix.
float OrbitalManeuverV2.forwardForceDampenent
Referenced by EngineBurn.
void OrbitalManeuverV2.Start()
References player.
void OrbitalManeuverV2.Update()
References axisOfRotation, DebugKeyboardInput, EngineBurn, inputDetectionUtils, MoveVelVectorTowardsDesinatedPos, InputDetectionUtils.ProcessTouchStateOnePoint, InputDetectionUtils.ScreenSideDetection, SetRotationalMatrix, SetRotationalSpeed.
void OrbitalManeuverV2.SetRotationalSpeed()
References rotationalSpeed.
Referenced by Update.
void OrbitalManeuverV2.MoveVelVectorTowardsDesinatedPos(Vector3 axisOfRotation)
Main method to handle rotation. Rotate around redefined axis of rotation at speed: rotationalSpeed The speed of rotation
Axis is set in code: private void SetAxisOfRotation() { axisOfRotation = inputDetectionUtils.MoveDirection.normalized; }
References inputDetectionUtils, points, rotatedPoint, rotationMatrixHelper, RotationMatrixHelper.TimesXYZ, InputDetectionUtils.TouchStopped.
Referenced by Update.
void OrbitalManeuverV2.SetRotationalMatrix()
Set properties defined in class:.
RotationMatrixHelper.cs
References CalculateFinalRotationVector, inputDetectionUtils, InputDetectionUtils.MoveDirection, rotationalSpeed, rotationalSpeedDampenent.
Referenced by Update.
void OrbitalManeuverV2.DebugKeyboardInput()
Setting the axis upon which player's heading vector will rotate around.
Currently = inputDetectionUtils.MoveDirection.normalized;
References axisOfRotation.
Referenced by Update.
Vector3 OrbitalManeuverV2.CalculateFinalRotationVector(Vector3 initialVector)
Calculate the axis of rotating (perpendicular to the swipe direction)
x' = x cos θ − y sin θ y' = x sin θ + +y cos θ
Referenced by SetRotationalMatrix.
void OrbitalManeuverV2.EngineBurn()
References InputDetectionUtils.ForceStrength, forwardForceDampenent, inputDetectionUtils, InputDetectionUtils.MoveDirection, player.
Referenced by Update.