InputDetectionUtils
float InputDetectionUtils.forceStrength
Vector3 InputDetectionUtils.MoveDirection
Referenced by CameraMovement.Camera3DMovement, OrbitalManeuverV2.EngineBurn, ProcessTouchStateOnePoint, ProcessTouchStateTwoPoints, OrbitalManeuverV2.SetRotationalMatrix.
Vector3 InputDetectionUtils.TouchEndPos
Referenced by ProcessTouchStateOnePoint, ProcessTouchStateTwoPoints.
Vector3 InputDetectionUtils.TouchStartPos
Referenced by CameraMovement.ProcessTilting, ProcessTouchStateOnePoint, ProcessTouchStateTwoPoints, PlayerUIDetection.RayCastToCollider, ScreenSideDetection, CameraMovement.Update.
string InputDetectionUtils.Begin
Referenced by CameraMovement.ProcessTilting.
string InputDetectionUtils.Moving
Referenced by CameraMovement.ProcessTilting.
string InputDetectionUtils.Holding
string InputDetectionUtils.Ended
string InputDetectionUtils.Canceled
float InputDetectionUtils.ForceStrength
Referenced by CameraMovement.Camera3DMovement, OrbitalManeuverV2.EngineBurn, ProcessTouchStateOnePoint, ProcessTouchStateTwoPoints.
int InputDetectionUtils.TouchCount
Referenced by CameraMovement.Camera3DMovement, TouchCountDetection.
bool InputDetectionUtils.TouchStopped
Referenced by OrbitalManeuverV2.MoveVelVectorTowardsDesinatedPos, ProcessTouchStateOnePoint, ProcessTouchStateTwoPoints.
void InputDetectionUtils.TouchCountDetection()
Current support for 2 touch states. Else return invlid / no touch state -1
References TouchCount.
string InputDetectionUtils.ProcessTouchStateOnePoint()
References ForceStrength, MoveDirection, TouchEndPos, TouchStartPos, TouchStopped.
Referenced by CameraMovement.ProcessTilting, OnScreenGUI.Update, PlayerUIDetection.Update, OrbitalManeuverV2.Update.
string InputDetectionUtils.ProcessTouchStateTwoPoints()
References ForceStrength, MoveDirection, TouchEndPos, TouchStartPos, TouchStopped.
string InputDetectionUtils.ScreenSideDetection(float screenWidth)
Detect which side of the screen touch is recordred Return string stating Left or Right
References TouchStartPos.
Referenced by OrbitalManeuverV2.Update.