ProBuilder2::EditorCommon::pb_VersionUtil
static bool ProBuilder2.EditorCommon.pb_VersionUtil.GetAboutEntry(out pb_AboutEntry about)
Get information from the currently installed ProBuilder version.
Referenced by ProBuilder2.EditorCommon.pb_AboutWindow.Init.
static bool ProBuilder2.EditorCommon.pb_VersionUtil.GetCurrent(out pb_VersionInfo version)
Referenced by ProBuilder2.EditorCommon.pb_UpdateCheck.Update.
static bool ProBuilder2.EditorCommon.pb_VersionUtil.FormatChangelog(string raw, out pb_VersionInfo version, out string formatted_changes)
Extracts and formats the latest changelog entry into rich text. Also grabs the version.
Referenced by ProBuilder2.EditorCommon.pb_UpdateCheck.Update.
static pb_AboutEntry ProBuilder2.EditorCommon.pb_VersionUtil.ParseAboutEntry(string path)
References ProBuilder2.EditorCommon.pb_AboutEntry.KEY_CHANGELOG, ProBuilder2.EditorCommon.pb_AboutEntry.KEY_DATE, ProBuilder2.EditorCommon.pb_AboutEntry.KEY_IDENTIFIER, ProBuilder2.EditorCommon.pb_AboutEntry.KEY_NAME, ProBuilder2.EditorCommon.pb_AboutEntry.KEY_VERSION.