WireframeRenderer
RendererType
bool WireframeRenderer.ShowBackFaces
Referenced by UpdateWireframeRendererMaterial.
Color WireframeRenderer.LineColor
Referenced by UpdateLineColor.
bool WireframeRenderer.Shaded
Referenced by UpateShaded.
Renderer WireframeRenderer.originalRenderer
Referenced by CreateWireframeRenderer, Validate.
Mesh WireframeRenderer.processedMesh
Referenced by CreateWireframeRenderer, GetProcessedMesh, Validate.
Renderer WireframeRenderer.wireframeRenderer
Referenced by CreateWireframeRenderer, OnDestroy, OnDisable, OnEnable, OnValidate, Validate.
Material WireframeRenderer.wireframeMaterialCull
Referenced by CreateMaterials, UpdateWireframeRendererMaterial.
Material WireframeRenderer.wireframeMaterialNoCull
Referenced by CreateMaterials, UpdateWireframeRendererMaterial.
RendererType WireframeRenderer.originalRendererType
Referenced by CreateWireframeRenderer, Validate.
void WireframeRenderer.Awake()
References Validate.
void WireframeRenderer.OnDestroy()
References wireframeRenderer.
void WireframeRenderer.Validate()
References CreateMaterials, CreateWireframeRenderer, GetProcessedMesh, OnValidate, originalRenderer, originalRendererType, processedMesh, wireframeRenderer.
Referenced by Awake.
void WireframeRenderer.CreateWireframeRenderer()
References MeshRenderer, originalRenderer, originalRendererType, processedMesh, SkinnedMeshRenderer, wireframeRenderer.
Referenced by Validate.
void WireframeRenderer.OnValidate()
References UpateShaded, UpdateLineColor, UpdateWireframeRendererMaterial, wireframeRenderer.
Referenced by OnEnable, Validate.
void WireframeRenderer.CreateMaterials()
References CreateWireframeMaterial, wireframeMaterialCull, wireframeMaterialNoCull.
Referenced by Validate.
void WireframeRenderer.UpdateWireframeRendererMaterial()
References ShowBackFaces, wireframeMaterialCull, wireframeMaterialNoCull.
Referenced by OnValidate.
void WireframeRenderer.UpdateLineColor()
References LineColor.
Referenced by OnValidate.
void WireframeRenderer.UpateShaded()
References Shaded.
Referenced by OnValidate.
Material WireframeRenderer.CreateWireframeMaterial(bool cull)
Referenced by CreateMaterials.
void WireframeRenderer.OnEnable()
References OnValidate, wireframeRenderer.
void WireframeRenderer.OnDisable()
References wireframeRenderer.
Mesh WireframeRenderer.GetProcessedMesh(Mesh mesh)
References processedMesh.
Referenced by Validate.