ResourcesDistribution
Transform ResourcesDistribution.pointsParent
Referenced by Start.
int ResourcesDistribution.accuracy
Referenced by HelperGenerateCirclePoints, SpawnPoints, Start.
GameObject ResourcesDistribution.player
Vector3 [] ResourcesDistribution.spawnPoints
Referenced by Start.
GameObject ResourcesDistribution.resourcePoint
Referenced by Start.
GameObject ResourcesDistribution.surfacePoint
Referenced by Start.
List<Vector3> ResourcesDistribution.points
Dictionary<string, PlanetResouces> ResourcesDistribution.pointsAndResources
List<Vector3> ResourcesDistribution.Points
Referenced by SpawnPoints.
Dictionary<string, PlanetResouces> ResourcesDistribution.PointsAndResources
Referenced by GetValueFromDictionary.
void ResourcesDistribution.Start()
References accuracy, HelperGenerateCirclePoints, InstantiatePoint, pointsParent, resourcePoint, spawnPoints, SpawnPoints, surfacePoint.
void ResourcesDistribution.Update()
void ResourcesDistribution.HelperGenerateCirclePoints(int accuracy)
References accuracy.
Referenced by Start.
void ResourcesDistribution.InstantiatePoint(GameObject point, Vector3[] positions, Transform parent)
Referenced by Start.
Vector3 [] ResourcesDistribution.SpawnPoints(int accuracy, int spawnRange)
References accuracy, Points.
Referenced by Start.
bool ResourcesDistribution.PlayerIsInResourcesZone(GameObject player, Vector3[] points)
PlanetResouces ResourcesDistribution.GetValueFromDictionary(string keyName)
References PointsAndResources.