OnGroundDetection
SphereCollider OnGroundDetection.surfaceCollider
bool OnGroundDetection.isLanded
Referenced by CurrentOverallStatus.DebugDisplayStatus, FreezeVelocityVector, LandedCondition, LiftOffCondition, OrbitalManeuver.Update.
bool OnGroundDetection.liftOff
Referenced by DebugUI.EnableLiftOff, OnCollisionExit, Update, OrbitalManeuver.Update.
bool OnGroundDetection.flag
GameObject OnGroundDetection.ship
Referenced by OnCollisionEnter.
bool OnGroundDetection.onCollosionEnterBool
Referenced by OnCollisionEnter, OnCollisionExit, Update.
bool OnGroundDetection.onCollosionExitBool
Referenced by OnCollisionEnter, OnCollisionExit, Update.
void OnGroundDetection.FixedUpdate()
References FreezeVelocityVector.
void OnGroundDetection.Update()
References LandedCondition, liftOff, LiftOffCondition, onCollosionEnterBool, onCollosionExitBool.
IEnumerator OnGroundDetection.FreezeVelocityVector()
References isLanded.
Referenced by FixedUpdate.
void OnGroundDetection.OnCollisionEnter(Collision collision)
References onCollosionEnterBool, onCollosionExitBool, ship.
void OnGroundDetection.OnCollisionExit(Collision collision)
References liftOff, onCollosionEnterBool, onCollosionExitBool.
IEnumerator OnGroundDetection.LiftOffCondition()
References isLanded.
Referenced by Update.
IEnumerator OnGroundDetection.LandedCondition()
References isLanded.
Referenced by Update.