LibNoise::Utils
const double LibNoise.Utils.Sqrt3
const int LibNoise.Utils.OctavesMaximum
Referenced by LibNoise.Generator.RidgedMultifractal.UpdateWeights.
const int LibNoise.Utils.GeneratorNoiseX
Referenced by LibNoise.Utils.GradientNoise3D, LibNoise.Utils.ValueNoise3DInt.
const int LibNoise.Utils.GeneratorNoiseY
Referenced by LibNoise.Utils.GradientNoise3D, LibNoise.Utils.ValueNoise3DInt.
const int LibNoise.Utils.GeneratorNoiseZ
Referenced by LibNoise.Utils.GradientNoise3D, LibNoise.Utils.ValueNoise3DInt.
const int LibNoise.Utils.GeneratorSeed
Referenced by LibNoise.Utils.GradientNoise3D, LibNoise.Utils.ValueNoise3DInt.
const int LibNoise.Utils.GeneratorShift
Referenced by LibNoise.Utils.GradientNoise3D.
readonly double [] LibNoise.Utils.Randoms
Referenced by LibNoise.Utils.GradientNoise3D.
static double LibNoise.Utils.GradientCoherentNoise3D(double x, double y, double z, long seed, QualityMode quality)
References LibNoise.Utils.GradientNoise3D, LibNoise.Utils.InterpolateLinear, LibNoise.Utils.MapCubicSCurve, LibNoise.Utils.MapQuinticSCurve.
static double LibNoise.Utils.GradientNoise3D(double fx, double fy, double fz, int ix, int iy, int iz, long seed)
References LibNoise.Utils.GeneratorNoiseX, LibNoise.Utils.GeneratorNoiseY, LibNoise.Utils.GeneratorNoiseZ, LibNoise.Utils.GeneratorSeed, LibNoise.Utils.GeneratorShift, LibNoise.Utils.Randoms.
Referenced by LibNoise.Utils.GradientCoherentNoise3D.
static double LibNoise.Utils.InterpolateCubic(double a, double b, double c, double d, double position)
static double LibNoise.Utils.InterpolateLinear(double a, double b, double position)
Referenced by LibNoise.Noise2D.GeneratePlanar, LibNoise.Utils.GradientCoherentNoise3D.
static double LibNoise.Utils.MakeInt32Range(double value)
Referenced by LibNoise.Generator.Checker.GetValue.
static double LibNoise.Utils.MapCubicSCurve(double value)
Referenced by LibNoise.Utils.GradientCoherentNoise3D.
static double LibNoise.Utils.MapQuinticSCurve(double value)
Referenced by LibNoise.Utils.GradientCoherentNoise3D.
static double LibNoise.Utils.ValueNoise3D(int x, int y, int z, int seed)
References LibNoise.Utils.ValueNoise3DInt.
static long LibNoise.Utils.ValueNoise3DInt(int x, int y, int z, int seed)
References LibNoise.Utils.GeneratorNoiseX, LibNoise.Utils.GeneratorNoiseY, LibNoise.Utils.GeneratorNoiseZ, LibNoise.Utils.GeneratorSeed.
Referenced by LibNoise.Utils.ValueNoise3D.