CubePlanet
Vector3 [] CubePlanet.directions
Referenced by ProcessNeighbours.
GameObject CubePlanet.planet
Referenced by CubePlanet.
CubeFace [] CubePlanet.faces
Referenced by CubePlanet, Update.
int CubePlanet.size
Referenced by CubePlanet, FinalizeFace, Update, WeldMeshes.
float CubePlanet.scale
Referenced by CubePlanet, FinalizeFace, Update.
LibNoise.Generator.Perlin CubePlanet.planes
Referenced by noise.
LibNoise.Generator.RidgedMultifractal CubePlanet.mountains
Referenced by noise.
float CubePlanet.noise(Vector3 point, int octaves, float lucanarity=2.0f, float gain=0.5f, float warp=0.25f)
References mountains, planes.
Referenced by FinalizeFace.
void CubePlanet.WeldMeshes(CubeFace face, Mesh neighbour, int neighbourDir)
References size.
Referenced by ProcessNeighbours.
void CubePlanet.ProcessNeighbours(CubeFace face)
References directions, CubeFace.mesh, CubeFace.neighbours, CubeFace.scale, WeldMeshes.
Referenced by FinalizeFace.
void CubePlanet.FinalizeFace(CubeFace face)
Turns a plane's vertices into a segment of a sphere
Processes neighbour faces in order to remove gaps/tears face The face in question (aint it an ugly one?)
References CubeFace.finalized, noise, ProcessNeighbours, scale, size.
Referenced by Update.
void CubePlanet.GetActiveQuadTreeFaces(CubeFace face, ref List< CubeFace > active)
Accumulates recursively all faces that have been created in a planet face
face 1 of 6 sides of the planet to recurse into active The recursive bag to collect into
References CubeFace.tree.
Referenced by Update.
CubePlanet.CubePlanet(string name, int size, float scale)
Creates a Planet using 6 planes normalized around the origin
name The planet name (duh) size Number of vertices in length and width for each CubeFace scale The scale of the planet (radius)
References faces, CubeFace.parent, planet, scale, size.
IEnumerator CubePlanet.Update(int f)
The coroutine planet update process Keeps track of LOD according to player distance to each CubeFace Processes a single face per call, subdivision delays coroutine for smoothing.
f The face index of the cube [0, 5]
References faces, FinalizeFace, GetActiveQuadTreeFaces, scale, size.
Referenced by PlanetGenerator.Update.