Planet
bool Planet.mobileShader
Referenced by InitMaterial, InitRingMaterial.
bool Planet.atmosphere
Referenced by InitMaterial.
bool Planet.updateChangeInRealTime
Referenced by LateUpdate.
Material Planet.PlanetMaterial
Referenced by LateUpdate, setShadow, Start.
Material Planet.ringMaterial
Referenced by LateUpdate, setShadow, Start.
float Planet.hdrExposure
Referenced by InitMaterial.
Color Planet.atmoColor
Referenced by InitMaterial.
float Planet.atmoStrength
Referenced by InitMaterial.
float Planet.kr
Referenced by InitMaterial.
float Planet.km
Referenced by InitMaterial.
float Planet.outerScaleFactor
Referenced by Start.
float Planet.innerRadius
Referenced by InitMaterial, InitRingMaterial, Start.
float Planet.outerRadius
Referenced by InitMaterial, Start.
float Planet.scaleDepth
Referenced by InitMaterial.
float Planet.scale
Referenced by InitMaterial, Start.
float Planet.gamma
Referenced by InitMaterial, Start.
Transform [] Planet.shadow
Referenced by InitMaterial, InitRingMaterial, setShadow.
int Planet.shadowNumber
Referenced by InitMaterial, InitRingMaterial, setShadowNumber.
void Planet.setShadowNumber(int n)
References shadowNumber.
void Planet.setShadow(Transform p, int n)
References InitMaterial, InitRingMaterial, PlanetMaterial, ringMaterial, shadow.
void Planet.Start()
References gamma, InitMaterial, InitRingMaterial, innerRadius, outerRadius, outerScaleFactor, PlanetMaterial, ringMaterial, scale.
void Planet.LateUpdate()
References InitMaterial, InitRingMaterial, PlanetMaterial, ringMaterial, updateChangeInRealTime.
void Planet.InitRingMaterial(Material mat)
References innerRadius, mobileShader, shadow, shadowNumber.
Referenced by LateUpdate, setShadow, Start.
void Planet.InitMaterial(Material mat)
References atmoColor, atmosphere, atmoStrength, gamma, hdrExposure, innerRadius, km, kr, mobileShader, outerRadius, scale, scaleDepth, shadow, shadowNumber.
Referenced by LateUpdate, setShadow, Start.