SpeedData
string SpeedData.deltaV
Referenced by GetDeltaVStringData.
string SpeedData.velocity
Referenced by GetVelocityStringData.
string SpeedData.acceleration
Referenced by GetAccelerationStringData.
KeplerOrbitMover SpeedData.dataClass
Referenced by Awake, GetAccelerationStringData.
ShipData SpeedData.shipData
Referenced by GetDeltaVStringData, Start.
OrbitalManeuver SpeedData.orbitalManeuver
Referenced by GetEnginePercentageInteger, GetEngineThrustPercentage, Start.
void SpeedData.Awake()
References dataClass.
void SpeedData.Start()
References orbitalManeuver, shipData.
float SpeedData.CalculateGetDeltaV(float exhaustVelocity, float shipFullMass, float shipEmptyMass)
Referenced by GetDeltaVStringData.
string SpeedData.GetVelocityStringData()
References velocity.
string SpeedData.GetAccelerationStringData()
References acceleration, dataClass, UnityEngine.Vector3d.magnitude, SimpleKeplerOrbits.KeplerOrbitMover.OrbitData, SimpleKeplerOrbits.KeplerOrbitData.SemiMajorAxis, SimpleKeplerOrbits.KeplerOrbitData.Velocity.
string SpeedData.GetDeltaVStringData()
References CalculateGetDeltaV, ShipData.CurrentEngineData, deltaV, EnginesData.EngineData.GetExhaustVelocity, shipData, ShipData.WeightData.
string SpeedData.GetEngineThrustPercentage()
References CalculateEngineThrustPercentage, OrbitalManeuver.ForceStrength, orbitalManeuver, OrbitalManeuver.VectorMagnitudeCap.
int SpeedData.GetEnginePercentageInteger()
References CalculateEngineThrustPercentage, OrbitalManeuver.ForceStrength, orbitalManeuver, OrbitalManeuver.VectorMagnitudeCap.
Referenced by ShipData.Update.
int SpeedData.CalculateEngineThrustPercentage(float inputVectorForceStrength, float vectorMagnitudeCap)
Referenced by GetEnginePercentageInteger, GetEngineThrustPercentage.