UnityEngine::Vector3d
double UnityEngine.Vector3d.x
Referenced by UnityEngine.Vector3d.Cross, SimpleKeplerOrbits.KeplerOrbitUtils.CrossProduct, UnityEngine.Vector3d.Distance, UnityEngine.Vector3d.Equals, UnityEngine.Vector3d.Lerp, UnityEngine.Vector3d.Max, UnityEngine.Vector3d.Min, UnityEngine.Vector3d.operator Vector2, UnityEngine.Vector3d.operator Vector3, UnityEngine.Vector3d.operator*, UnityEngine.Vector3d.operator+, UnityEngine.Vector3d.operator-, UnityEngine.Vector3d.operator/, SimpleKeplerOrbits.KeplerOrbitUtils.RotateVectorByAngle, UnityEngine.Vector3d.Scale, SimpleOrbitDataDisplay.Update, UnityEngine.Vector3d.Vector3d.
double UnityEngine.Vector3d.y
Referenced by UnityEngine.Vector3d.Cross, SimpleKeplerOrbits.KeplerOrbitUtils.CrossProduct, UnityEngine.Vector3d.Distance, UnityEngine.Vector3d.GetHashCode, UnityEngine.Vector3d.Lerp, UnityEngine.Vector3d.operator Vector2, UnityEngine.Vector3d.operator Vector3, UnityEngine.Vector3d.operator*, UnityEngine.Vector3d.operator+, UnityEngine.Vector3d.operator-, UnityEngine.Vector3d.operator/, SimpleKeplerOrbits.KeplerOrbitUtils.RotateVectorByAngle, UnityEngine.Vector3d.Scale, UnityEngine.Vector3d.ToString, SimpleOrbitDataDisplay.Update, UnityEngine.Vector3d.Vector3d.
double UnityEngine.Vector3d.z
Referenced by UnityEngine.Vector3d.Cross, SimpleKeplerOrbits.KeplerOrbitUtils.CrossProduct, UnityEngine.Vector3d.Distance, UnityEngine.Vector3d.Lerp, UnityEngine.Vector3d.Max, UnityEngine.Vector3d.Min, UnityEngine.Vector3d.operator Vector3, UnityEngine.Vector3d.operator*, UnityEngine.Vector3d.operator+, UnityEngine.Vector3d.operator-, UnityEngine.Vector3d.operator/, SimpleKeplerOrbits.KeplerOrbitUtils.RotateVectorByAngle, UnityEngine.Vector3d.Scale, UnityEngine.Vector3d.Vector3d.
double UnityEngine.Vector3d.this[int index]
Vector3d UnityEngine.Vector3d.normalized
Referenced by UnityEngine.Vector3d.Angle.
double UnityEngine.Vector3d.magnitude
Referenced by SpeedData.GetAccelerationStringData, UnityEngine.Vector3d.MoveTowards.
double UnityEngine.Vector3d.sqrMagnitude
Referenced by SimpleKeplerOrbits.KeplerOrbitData.CalculateNewOrbitData, UnityEngine.Vector3d.ClampMagnitude.
Vector3d UnityEngine.Vector3d.zero
Referenced by UnityEngine.Vector3d.Normalize, UnityEngine.Vector3d.Project.
Vector3d UnityEngine.Vector3d.one
Vector3d UnityEngine.Vector3d.forward
Vector3d UnityEngine.Vector3d.back
Vector3d UnityEngine.Vector3d.up
Vector3d UnityEngine.Vector3d.down
Vector3d UnityEngine.Vector3d.left
Vector3d UnityEngine.Vector3d.right
Vector3d UnityEngine.Vector3d.fwd
UnityEngine.Vector3d.Vector3d(double x, double y, double z)
References UnityEngine.Vector3d.x, UnityEngine.Vector3d.y, UnityEngine.Vector3d.z.
Referenced by UnityEngine.Vector3d.Cross, UnityEngine.Vector3d.Distance, UnityEngine.Vector3d.Equals, UnityEngine.Vector3d.Lerp, UnityEngine.Vector3d.Max, UnityEngine.Vector3d.Min, UnityEngine.Vector3d.operator*, UnityEngine.Vector3d.operator+, UnityEngine.Vector3d.operator-, UnityEngine.Vector3d.operator/, UnityEngine.Vector3d.OrthoNormalize, UnityEngine.Vector3d.RotateTowards, UnityEngine.Vector3d.Scale, UnityEngine.Vector3d.Slerp.
UnityEngine.Vector3d.Vector3d(float x, float y, float z)
UnityEngine.Vector3d.Vector3d(Vector3 v3)
UnityEngine.Vector3d.Vector3d(double x, double y)
References UnityEngine.Vector3d.x, UnityEngine.Vector3d.y.
void UnityEngine.Vector3d.Set(double new_x, double new_y, double new_z)
void UnityEngine.Vector3d.Scale(Vector3d scale)
override int UnityEngine.Vector3d.GetHashCode()
References UnityEngine.Vector3d.y.
override bool UnityEngine.Vector3d.Equals(object other)
References UnityEngine.Vector3d.Vector3d, UnityEngine.Vector3d.x.
void UnityEngine.Vector3d.Normalize()
References UnityEngine.Vector3d.zero.
override string UnityEngine.Vector3d.ToString()
string UnityEngine.Vector3d.ToString(string format)
References UnityEngine.Vector3d.y.
static Vector3d UnityEngine.Vector3d.operator+(Vector3d a, Vector3d b)
References UnityEngine.Vector3d.Vector3d, UnityEngine.Vector3d.x, UnityEngine.Vector3d.y, UnityEngine.Vector3d.z.
static Vector3d UnityEngine.Vector3d.operator-(Vector3d a, Vector3d b)
References UnityEngine.Vector3d.Vector3d, UnityEngine.Vector3d.x, UnityEngine.Vector3d.y, UnityEngine.Vector3d.z.
static Vector3d UnityEngine.Vector3d.operator-(Vector3d a)
References UnityEngine.Vector3d.Vector3d, UnityEngine.Vector3d.x, UnityEngine.Vector3d.y, UnityEngine.Vector3d.z.
static Vector3d UnityEngine.Vector3d.operator*(Vector3d a, double d)
References UnityEngine.Vector3d.Vector3d, UnityEngine.Vector3d.x, UnityEngine.Vector3d.y, UnityEngine.Vector3d.z.
static Vector3d UnityEngine.Vector3d.operator*(double d, Vector3d a)
References UnityEngine.Vector3d.Vector3d, UnityEngine.Vector3d.x, UnityEngine.Vector3d.y, UnityEngine.Vector3d.z.
static Vector3d UnityEngine.Vector3d.operator/(Vector3d a, double d)
References UnityEngine.Vector3d.Vector3d, UnityEngine.Vector3d.x, UnityEngine.Vector3d.y, UnityEngine.Vector3d.z.
static bool UnityEngine.Vector3d.operator==(Vector3d lhs, Vector3d rhs)
static bool UnityEngine.Vector3d.operator!=(Vector3d lhs, Vector3d rhs)
static UnityEngine.Vector3d.operator Vector3(Vector3d vector3d)
References UnityEngine.Vector3d.x, UnityEngine.Vector3d.y, UnityEngine.Vector3d.z.
static UnityEngine.Vector3d.operator Vector2(Vector3d vector3d)
References UnityEngine.Vector3d.x, UnityEngine.Vector3d.y.
static Vector3d UnityEngine.Vector3d.Lerp(Vector3d from, Vector3d to, double t)
References UnityEngine.Vector3d.Vector3d, UnityEngine.Vector3d.x, UnityEngine.Vector3d.y, UnityEngine.Vector3d.z.
static Vector3d UnityEngine.Vector3d.Slerp(Vector3d from, Vector3d to, double t)
References UnityEngine.Vector3d.Vector3d.
static void UnityEngine.Vector3d.OrthoNormalize(ref Vector3d normal, ref Vector3d tangent)
References UnityEngine.Vector3d.Vector3d.
static void UnityEngine.Vector3d.OrthoNormalize(ref Vector3d normal, ref Vector3d tangent, ref Vector3d binormal)
References UnityEngine.Vector3d.Vector3d.
static Vector3d UnityEngine.Vector3d.MoveTowards(Vector3d current, Vector3d target, double maxDistanceDelta)
References UnityEngine.Vector3d.magnitude.
static Vector3d UnityEngine.Vector3d.RotateTowards(Vector3d current, Vector3d target, double maxRadiansDelta, double maxMagnitudeDelta)
References UnityEngine.Vector3d.Vector3d.
static Vector3d UnityEngine.Vector3d.SmoothDamp(Vector3d current, Vector3d target, ref Vector3d currentVelocity, double smoothTime, double maxSpeed)
References UnityEngine.Vector3d.SmoothDamp.
Referenced by UnityEngine.Vector3d.SmoothDamp.
static Vector3d UnityEngine.Vector3d.SmoothDamp(Vector3d current, Vector3d target, ref Vector3d currentVelocity, double smoothTime)
References UnityEngine.Vector3d.SmoothDamp.
static Vector3d UnityEngine.Vector3d.SmoothDamp(Vector3d current, Vector3d target, ref Vector3d currentVelocity, double smoothTime, double maxSpeed, double deltaTime)
References UnityEngine.Vector3d.Dot.
static Vector3d UnityEngine.Vector3d.Scale(Vector3d a, Vector3d b)
References UnityEngine.Vector3d.Vector3d, UnityEngine.Vector3d.x, UnityEngine.Vector3d.y, UnityEngine.Vector3d.z.
static Vector3d UnityEngine.Vector3d.Cross(Vector3d lhs, Vector3d rhs)
References UnityEngine.Vector3d.Vector3d, UnityEngine.Vector3d.x, UnityEngine.Vector3d.y, UnityEngine.Vector3d.z.
static Vector3d UnityEngine.Vector3d.Reflect(Vector3d inDirection, Vector3d inNormal)
static Vector3d UnityEngine.Vector3d.Normalize(Vector3d value)
References UnityEngine.Vector3d.zero.
static double UnityEngine.Vector3d.Dot(Vector3d lhs, Vector3d rhs)
Referenced by UnityEngine.Vector3d.Angle, UnityEngine.Vector3d.SmoothDamp.
static Vector3d UnityEngine.Vector3d.Project(Vector3d vector, Vector3d onNormal)
References UnityEngine.Vector3d.zero.
static Vector3d UnityEngine.Vector3d.Exclude(Vector3d excludeThis, Vector3d fromThat)
static double UnityEngine.Vector3d.Distance(Vector3d a, Vector3d b)
References UnityEngine.Vector3d.Vector3d, UnityEngine.Vector3d.x, UnityEngine.Vector3d.y, UnityEngine.Vector3d.z.
static Vector3d UnityEngine.Vector3d.ClampMagnitude(Vector3d vector, double maxLength)
References UnityEngine.Vector3d.sqrMagnitude.
static double UnityEngine.Vector3d.Angle(Vector3d from, Vector3d to)
References UnityEngine.Vector3d.Dot, UnityEngine.Vector3d.normalized.
static double UnityEngine.Vector3d.Magnitude(Vector3d a)
static double UnityEngine.Vector3d.SqrMagnitude(Vector3d a)
static Vector3d UnityEngine.Vector3d.Min(Vector3d lhs, Vector3d rhs)
References UnityEngine.Vector3d.Vector3d, UnityEngine.Vector3d.x, UnityEngine.Vector3d.z.
static Vector3d UnityEngine.Vector3d.Max(Vector3d lhs, Vector3d rhs)
References UnityEngine.Vector3d.Vector3d, UnityEngine.Vector3d.x, UnityEngine.Vector3d.z.