SimpleKeplerOrbits::KeplerOrbitData
double SimpleKeplerOrbits.KeplerOrbitData.GravConst
Referenced by SimpleKeplerOrbits.KeplerOrbitData.CalculateNewOrbitData, SimpleKeplerOrbits.KeplerOrbitData.GetVelocityAtTrueAnomaly, SimpleKeplerOrbits.KeplerOrbitMover.Update, SimpleKeplerOrbits.KeplerOrbitData.UpdateOrbitAnomaliesByTime.
Vector3d SimpleKeplerOrbits.KeplerOrbitData.EclipticNormal
Referenced by SimpleKeplerOrbits.KeplerOrbitData.CalculateNewOrbitData, SimpleKeplerOrbits.KeplerOrbitData.GetAscendingNode, SimpleKeplerOrbits.KeplerOrbitData.GetDescendingNode.
Vector3d SimpleKeplerOrbits.KeplerOrbitData.EclipticUp
Referenced by SimpleKeplerOrbits.KeplerOrbitData.CalculateNewOrbitData.
Vector3d SimpleKeplerOrbits.KeplerOrbitData.Position
Referenced by SimpleKeplerOrbits.KeplerOrbitData.CalculateNewOrbitData, SimpleKeplerOrbits.KeplerOrbitMover.ForceUpdateViewFromInternalState, SimpleKeplerOrbits.KeplerOrbitData.GetCentralPosition, SimpleKeplerOrbits.KeplerOrbitData.RotateOrbit, SimpleKeplerOrbits.KeplerOrbitData.SetPositionByCurrentAnomaly, SimpleKeplerOrbits.KeplerOrbitMover.Update.
double SimpleKeplerOrbits.KeplerOrbitData.AttractorDistance
Referenced by SimpleKeplerOrbits.KeplerOrbitData.CalculateNewOrbitData.
double SimpleKeplerOrbits.KeplerOrbitData.AttractorMass
Referenced by SimpleKeplerOrbits.KeplerOrbitData.CalculateNewOrbitData, SimpleKeplerOrbits.KeplerOrbitData.GetVelocityAtTrueAnomaly, SimpleKeplerOrbits.KeplerOrbitMover.Update, SimpleKeplerOrbits.KeplerOrbitData.UpdateOrbitAnomaliesByTime.
Vector3d SimpleKeplerOrbits.KeplerOrbitData.Velocity
Referenced by SimpleKeplerOrbits.KeplerOrbitData.CalculateNewOrbitData, SimpleKeplerOrbits.KeplerOrbitMover.ForceUpdateViewFromInternalState, SimpleKeplerOrbits.KeplerOrbitMover.OrbitUpdateLoop, SimpleKeplerOrbits.KeplerOrbitData.RotateOrbit, SimpleKeplerOrbits.KeplerOrbitMover.SetAutoCircleOrbit, SimpleKeplerOrbits.KeplerOrbitData.SetVelocityByCurrentAnomaly, SimpleKeplerOrbits.KeplerOrbitMover.Update.
double SimpleKeplerOrbits.KeplerOrbitData.SemiMinorAxis
Referenced by SimpleKeplerOrbits.KeplerOrbitData.CalculateNewOrbitData, SimpleKeplerOrbits.KeplerOrbitData.GetCentralPositionAtEccentricAnomaly, SimpleKeplerOrbits.KeplerOrbitData.SetEccentricity.
double SimpleKeplerOrbits.KeplerOrbitData.SemiMajorAxis
Referenced by SimpleKeplerOrbits.KeplerOrbitData.CalculateNewOrbitData, SimpleKeplerOrbits.KeplerOrbitData.GetCentralPositionAtEccentricAnomaly, SimpleKeplerOrbits.KeplerOrbitData.GetOrbitPoints, SimpleKeplerOrbits.KeplerOrbitData.GetOrbitPointsNoAlloc, SimpleKeplerOrbits.KeplerOrbitData.SetEccentricity, SimpleKeplerOrbits.KeplerOrbitData.UpdateOrbitAnomaliesByTime.
double SimpleKeplerOrbits.KeplerOrbitData.FocalParameter
Referenced by SimpleKeplerOrbits.KeplerOrbitData.CalculateNewOrbitData, SimpleKeplerOrbits.KeplerOrbitData.GetVelocityAtTrueAnomaly, SimpleKeplerOrbits.KeplerOrbitData.SetEccentricity.
double SimpleKeplerOrbits.KeplerOrbitData.Eccentricity
Referenced by SimpleKeplerOrbits.KeplerOrbitData.CalculateNewOrbitData, SimpleKeplerOrbits.KeplerOrbitData.GetAscendingNode, SimpleKeplerOrbits.KeplerOrbitData.GetCentralPositionAtEccentricAnomaly, SimpleKeplerOrbits.KeplerOrbitData.GetCentralPositionAtTrueAnomaly, SimpleKeplerOrbits.KeplerOrbitData.GetDescendingNode, SimpleKeplerOrbits.KeplerOrbitData.GetOrbitPoints, SimpleKeplerOrbits.KeplerOrbitData.GetOrbitPointsNoAlloc, SimpleKeplerOrbits.KeplerOrbitData.GetVelocityAtEccentricAnomaly, SimpleKeplerOrbits.KeplerOrbitData.GetVelocityAtTrueAnomaly, SimpleKeplerOrbits.KeplerOrbitData.SetEccentricAnomaly, SimpleKeplerOrbits.KeplerOrbitData.SetEccentricity, SimpleKeplerOrbits.KeplerOrbitData.SetMeanAnomaly, SimpleKeplerOrbits.KeplerOrbitData.SetTrueAnomaly, SimpleKeplerOrbits.KeplerOrbitData.UpdateOrbitAnomaliesByTime.
double SimpleKeplerOrbits.KeplerOrbitData.EnergyTotal
Referenced by SimpleKeplerOrbits.KeplerOrbitData.CalculateNewOrbitData.
double SimpleKeplerOrbits.KeplerOrbitData.Period
Referenced by SimpleKeplerOrbits.KeplerOrbitData.CalculateNewOrbitData, SimpleKeplerOrbits.KeplerOrbitData.UpdateOrbitAnomaliesByTime.
double SimpleKeplerOrbits.KeplerOrbitData.TrueAnomaly
Referenced by SimpleKeplerOrbits.KeplerOrbitData.CalculateNewOrbitData, SimpleKeplerOrbits.KeplerOrbitData.SetEccentricAnomaly, SimpleKeplerOrbits.KeplerOrbitData.SetEccentricity, SimpleKeplerOrbits.KeplerOrbitData.SetMeanAnomaly, SimpleKeplerOrbits.KeplerOrbitData.UpdateOrbitAnomaliesByTime.
double SimpleKeplerOrbits.KeplerOrbitData.MeanAnomaly
Referenced by SimpleKeplerOrbits.KeplerOrbitData.CalculateNewOrbitData, SimpleKeplerOrbits.KeplerOrbitData.SetEccentricAnomaly, SimpleKeplerOrbits.KeplerOrbitData.SetEccentricity, SimpleKeplerOrbits.KeplerOrbitData.SetMeanAnomaly, SimpleKeplerOrbits.KeplerOrbitData.SetTrueAnomaly, SimpleKeplerOrbits.KeplerOrbitData.UpdateOrbitAnomaliesByTime.
double SimpleKeplerOrbits.KeplerOrbitData.EccentricAnomaly
Referenced by SimpleKeplerOrbits.KeplerOrbitData.CalculateNewOrbitData, SimpleKeplerOrbits.KeplerOrbitData.SetEccentricAnomaly, SimpleKeplerOrbits.KeplerOrbitData.SetEccentricity, SimpleKeplerOrbits.KeplerOrbitData.SetMeanAnomaly, SimpleKeplerOrbits.KeplerOrbitData.SetPositionByCurrentAnomaly, SimpleKeplerOrbits.KeplerOrbitData.SetTrueAnomaly, SimpleKeplerOrbits.KeplerOrbitData.SetVelocityByCurrentAnomaly, SimpleKeplerOrbits.KeplerOrbitData.UpdateOrbitAnomaliesByTime.
double SimpleKeplerOrbits.KeplerOrbitData.SquaresConstant
Vector3d SimpleKeplerOrbits.KeplerOrbitData.Periapsis
Referenced by SimpleKeplerOrbits.KeplerOrbitData.CalculateNewOrbitData.
double SimpleKeplerOrbits.KeplerOrbitData.PeriapsisDistance
Referenced by SimpleKeplerOrbits.KeplerOrbitData.CalculateNewOrbitData, SimpleKeplerOrbits.KeplerOrbitData.GetOrbitPoints, SimpleKeplerOrbits.KeplerOrbitData.GetOrbitPointsNoAlloc, SimpleKeplerOrbits.KeplerOrbitData.SetEccentricity.
Vector3d SimpleKeplerOrbits.KeplerOrbitData.Apoapsis
Referenced by SimpleKeplerOrbits.KeplerOrbitData.CalculateNewOrbitData.
double SimpleKeplerOrbits.KeplerOrbitData.ApoapsisDistance
Referenced by SimpleKeplerOrbits.KeplerOrbitData.CalculateNewOrbitData, SimpleKeplerOrbits.KeplerOrbitData.GetOrbitPoints, SimpleKeplerOrbits.KeplerOrbitData.GetOrbitPointsNoAlloc.
Vector3d SimpleKeplerOrbits.KeplerOrbitData.CenterPoint
Referenced by SimpleKeplerOrbits.KeplerOrbitData.CalculateNewOrbitData, SimpleKeplerOrbits.KeplerOrbitData.GetAscendingNode, SimpleKeplerOrbits.KeplerOrbitData.GetCentralPosition, SimpleKeplerOrbits.KeplerOrbitData.GetDescendingNode, SimpleKeplerOrbits.KeplerOrbitData.GetFocalPositionAtEccentricAnomaly, SimpleKeplerOrbits.KeplerOrbitData.GetFocalPositionAtTrueAnomaly, SimpleKeplerOrbits.KeplerOrbitData.SetEccentricity.
double SimpleKeplerOrbits.KeplerOrbitData.OrbitCompressionRatio
Referenced by SimpleKeplerOrbits.KeplerOrbitData.CalculateNewOrbitData.
Vector3d SimpleKeplerOrbits.KeplerOrbitData.OrbitNormal
Referenced by SimpleKeplerOrbits.KeplerOrbitData.CalculateNewOrbitData, SimpleKeplerOrbits.KeplerOrbitData.GetAscendingNode, SimpleKeplerOrbits.KeplerOrbitData.GetDescendingNode.
Vector3d SimpleKeplerOrbits.KeplerOrbitData.SemiMinorAxisBasis
Referenced by SimpleKeplerOrbits.KeplerOrbitData.CalculateNewOrbitData, SimpleKeplerOrbits.KeplerOrbitData.GetCentralPositionAtEccentricAnomaly, SimpleKeplerOrbits.KeplerOrbitData.GetVelocityAtTrueAnomaly.
Vector3d SimpleKeplerOrbits.KeplerOrbitData.SemiMajorAxisBasis
Referenced by SimpleKeplerOrbits.KeplerOrbitData.CalculateNewOrbitData, SimpleKeplerOrbits.KeplerOrbitData.GetAscendingNode, SimpleKeplerOrbits.KeplerOrbitData.GetCentralPositionAtEccentricAnomaly, SimpleKeplerOrbits.KeplerOrbitData.GetDescendingNode, SimpleKeplerOrbits.KeplerOrbitData.GetVelocityAtTrueAnomaly, SimpleKeplerOrbits.KeplerOrbitData.SetEccentricity.
double SimpleKeplerOrbits.KeplerOrbitData.Inclination
The orbit inclination in radians relative to ecliptic plane.
Referenced by SimpleKeplerOrbits.KeplerOrbitData.CalculateNewOrbitData.
double SimpleKeplerOrbits.KeplerOrbitData.OrbitNormalDotEclipticNormal
if > 0, then orbit motion is clockwise
Referenced by SimpleKeplerOrbits.KeplerOrbitData.CalculateNewOrbitData.
bool SimpleKeplerOrbits.KeplerOrbitData.IsValidOrbit
Is orbit state valid and error-free.
true if this instance is valid orbit; otherwise, false.
Referenced by SimpleKeplerOrbits.KeplerOrbitMover.OrbitUpdateLoop, SimpleKeplerOrbits.KeplerOrbitData.SetEccentricAnomaly, SimpleKeplerOrbits.KeplerOrbitData.SetEccentricity, SimpleKeplerOrbits.KeplerOrbitData.SetMeanAnomaly, SimpleKeplerOrbits.KeplerOrbitData.SetTrueAnomaly.
void SimpleKeplerOrbits.KeplerOrbitData.CalculateNewOrbitData()
Calculates the full state of orbit from current body position, attractor position, attractor mass, velocity, and gravConstant.
References SimpleKeplerOrbits.KeplerOrbitData.Apoapsis, SimpleKeplerOrbits.KeplerOrbitData.ApoapsisDistance, SimpleKeplerOrbits.KeplerOrbitData.AttractorDistance, SimpleKeplerOrbits.KeplerOrbitData.AttractorMass, SimpleKeplerOrbits.KeplerOrbitData.CenterPoint, SimpleKeplerOrbits.KeplerOrbitUtils.CrossProduct, SimpleKeplerOrbits.KeplerOrbitUtils.Deg2Rad, SimpleKeplerOrbits.KeplerOrbitUtils.DotProduct, SimpleKeplerOrbits.KeplerOrbitData.EccentricAnomaly, SimpleKeplerOrbits.KeplerOrbitData.Eccentricity, SimpleKeplerOrbits.KeplerOrbitData.EclipticNormal, SimpleKeplerOrbits.KeplerOrbitData.EclipticUp, SimpleKeplerOrbits.KeplerOrbitData.EnergyTotal, SimpleKeplerOrbits.KeplerOrbitData.FocalParameter, SimpleKeplerOrbits.KeplerOrbitData.GravConst, SimpleKeplerOrbits.KeplerOrbitData.Inclination, SimpleKeplerOrbits.KeplerOrbitData.MeanAnomaly, SimpleKeplerOrbits.KeplerOrbitData.OrbitCompressionRatio, SimpleKeplerOrbits.KeplerOrbitData.OrbitNormal, SimpleKeplerOrbits.KeplerOrbitData.OrbitNormalDotEclipticNormal, SimpleKeplerOrbits.KeplerOrbitData.Periapsis, SimpleKeplerOrbits.KeplerOrbitData.PeriapsisDistance, SimpleKeplerOrbits.KeplerOrbitData.Period, SimpleKeplerOrbits.KeplerOrbitData.Position, SimpleKeplerOrbits.KeplerOrbitData.SemiMajorAxis, SimpleKeplerOrbits.KeplerOrbitData.SemiMajorAxisBasis, SimpleKeplerOrbits.KeplerOrbitData.SemiMinorAxis, SimpleKeplerOrbits.KeplerOrbitData.SemiMinorAxisBasis, UnityEngine.Vector3d.sqrMagnitude, SimpleKeplerOrbits.KeplerOrbitData.TrueAnomaly, SimpleKeplerOrbits.KeplerOrbitData.Velocity.
Referenced by SimpleKeplerOrbits.KeplerOrbitData.RotateOrbit, SimpleKeplerOrbits.KeplerOrbitData.SetEccentricity.
Vector3d SimpleKeplerOrbits.KeplerOrbitData.GetVelocityAtEccentricAnomaly(double eccentricAnomaly)
Gets the velocity vector value at eccentric anomaly.
eccentricAnomaly The eccentric anomaly. Velocity vector.
References SimpleKeplerOrbits.KeplerOrbitUtils.ConvertEccentricToTrueAnomaly, SimpleKeplerOrbits.KeplerOrbitData.Eccentricity, SimpleKeplerOrbits.KeplerOrbitData.GetVelocityAtTrueAnomaly.
Referenced by SimpleKeplerOrbits.KeplerOrbitData.SetVelocityByCurrentAnomaly.
Vector3d SimpleKeplerOrbits.KeplerOrbitData.GetVelocityAtTrueAnomaly(double trueAnomaly)
Gets the velocity value at true anomaly.
trueAnomaly The true anomaly. Velocity vector.
References SimpleKeplerOrbits.KeplerOrbitData.AttractorMass, SimpleKeplerOrbits.KeplerOrbitData.Eccentricity, SimpleKeplerOrbits.KeplerOrbitData.FocalParameter, SimpleKeplerOrbits.KeplerOrbitData.GravConst, SimpleKeplerOrbits.KeplerOrbitData.SemiMajorAxisBasis, SimpleKeplerOrbits.KeplerOrbitData.SemiMinorAxisBasis.
Referenced by SimpleKeplerOrbits.KeplerOrbitData.GetVelocityAtEccentricAnomaly.
Vector3d SimpleKeplerOrbits.KeplerOrbitData.GetCentralPositionAtTrueAnomaly(double trueAnomaly)
Gets the central position at true anomaly.
trueAnomaly The true anomaly. Position relative to orbit center. Note: central position is not same as focal position.
References SimpleKeplerOrbits.KeplerOrbitData.Eccentricity, SimpleKeplerOrbits.KeplerOrbitData.GetCentralPositionAtEccentricAnomaly.
Referenced by SimpleKeplerOrbits.KeplerOrbitData.GetFocalPositionAtTrueAnomaly.
Vector3d SimpleKeplerOrbits.KeplerOrbitData.GetCentralPositionAtEccentricAnomaly(double eccentricAnomaly)
Gets the central position at eccentric anomaly.
eccentricAnomaly The eccentric anomaly. Position relative to orbit center. Note: central position is not same as focal position.
References SimpleKeplerOrbits.KeplerOrbitData.Eccentricity, SimpleKeplerOrbits.KeplerOrbitData.SemiMajorAxis, SimpleKeplerOrbits.KeplerOrbitData.SemiMajorAxisBasis, SimpleKeplerOrbits.KeplerOrbitData.SemiMinorAxis, SimpleKeplerOrbits.KeplerOrbitData.SemiMinorAxisBasis.
Referenced by SimpleKeplerOrbits.KeplerOrbitData.GetCentralPositionAtTrueAnomaly, SimpleKeplerOrbits.KeplerOrbitData.GetFocalPositionAtEccentricAnomaly.
Vector3d SimpleKeplerOrbits.KeplerOrbitData.GetFocalPositionAtEccentricAnomaly(double eccentricAnomaly)
Gets the focal position at eccentric anomaly.
eccentricAnomaly The eccentric anomaly. Position relative to attractor (focus).
References SimpleKeplerOrbits.KeplerOrbitData.CenterPoint, SimpleKeplerOrbits.KeplerOrbitData.GetCentralPositionAtEccentricAnomaly.
Referenced by SimpleKeplerOrbits.KeplerOrbitData.GetAscendingNode, SimpleKeplerOrbits.KeplerOrbitData.GetDescendingNode, SimpleKeplerOrbits.KeplerOrbitData.GetOrbitPoints, SimpleKeplerOrbits.KeplerOrbitData.GetOrbitPointsNoAlloc, SimpleKeplerOrbits.KeplerOrbitData.SetPositionByCurrentAnomaly.
Vector3d SimpleKeplerOrbits.KeplerOrbitData.GetFocalPositionAtTrueAnomaly(double trueAnomaly)
Gets the focal position at true anomaly.
trueAnomaly The true anomaly. Position relative to attractor (focus).
References SimpleKeplerOrbits.KeplerOrbitData.CenterPoint, SimpleKeplerOrbits.KeplerOrbitData.GetCentralPositionAtTrueAnomaly.
Referenced by SimpleKeplerOrbits.KeplerOrbitData.GetOrbitPoints, SimpleKeplerOrbits.KeplerOrbitData.GetOrbitPointsNoAlloc.
Vector3d SimpleKeplerOrbits.KeplerOrbitData.GetCentralPosition()
Gets the central position.
Position relative to orbit center. Note: central position is not same as focal position.
References SimpleKeplerOrbits.KeplerOrbitData.CenterPoint, SimpleKeplerOrbits.KeplerOrbitData.Position.
Vector3d [] SimpleKeplerOrbits.KeplerOrbitData.GetOrbitPoints(int pointsCount=50, double maxDistance=1000d)
Gets calculated orbit points with defined precision.
pointsCount The points count. maxDistance The maximum distance of points. Array of orbit curve points.
Referenced by SimpleKeplerOrbits.KeplerOrbitData.GetOrbitPoints.
Vector3d [] SimpleKeplerOrbits.KeplerOrbitData.GetOrbitPoints(int pointsCount, Vector3d origin, double maxDistance=1000d)
Gets calculated orbit points with defined precision.
pointsCount The points count. origin The origin. maxDistance The maximum distance. Array of orbit curve points.
References SimpleKeplerOrbits.KeplerOrbitData.ApoapsisDistance, SimpleKeplerOrbits.KeplerOrbitData.Eccentricity, SimpleKeplerOrbits.KeplerOrbitData.GetFocalPositionAtEccentricAnomaly, SimpleKeplerOrbits.KeplerOrbitData.GetFocalPositionAtTrueAnomaly, SimpleKeplerOrbits.KeplerOrbitData.PeriapsisDistance, SimpleKeplerOrbits.KeplerOrbitUtils.PI_2, SimpleKeplerOrbits.KeplerOrbitData.SemiMajorAxis.
Vector3 [] SimpleKeplerOrbits.KeplerOrbitData.GetOrbitPoints(int pointsCount=50, float maxDistance=1000f)
Gets calculated orbit points with defined precision.
pointsCount The points count. maxDistance The maximum distance. Array of orbit curve points.
References SimpleKeplerOrbits.KeplerOrbitData.GetOrbitPoints.
Vector3 [] SimpleKeplerOrbits.KeplerOrbitData.GetOrbitPoints(int pointsCount, Vector3 origin, float maxDistance=1000f)
Gets calculated orbit points with defined precision.
pointsCount The points count. origin The origin. maxDistance The maximum distance. Array of orbit curve points.
References SimpleKeplerOrbits.KeplerOrbitData.ApoapsisDistance, SimpleKeplerOrbits.KeplerOrbitData.Eccentricity, SimpleKeplerOrbits.KeplerOrbitData.GetFocalPositionAtEccentricAnomaly, SimpleKeplerOrbits.KeplerOrbitData.GetFocalPositionAtTrueAnomaly, SimpleKeplerOrbits.KeplerOrbitData.PeriapsisDistance, SimpleKeplerOrbits.KeplerOrbitUtils.PI_2, SimpleKeplerOrbits.KeplerOrbitData.SemiMajorAxis.
void SimpleKeplerOrbits.KeplerOrbitData.GetOrbitPointsNoAlloc(ref Vector3[] orbitPoints, int pointsCount, Vector3 origin, float maxDistance=1000f)
Gets the orbit points without unnecessary memory alloc for resulting array. However, memory allocation may occur if resulting array has not correct lenght.
orbitPoints The orbit points. pointsCount The points count. origin The origin. maxDistance The maximum distance.
References SimpleKeplerOrbits.KeplerOrbitData.ApoapsisDistance, SimpleKeplerOrbits.KeplerOrbitData.Eccentricity, SimpleKeplerOrbits.KeplerOrbitData.GetFocalPositionAtEccentricAnomaly, SimpleKeplerOrbits.KeplerOrbitData.GetFocalPositionAtTrueAnomaly, SimpleKeplerOrbits.KeplerOrbitData.PeriapsisDistance, SimpleKeplerOrbits.KeplerOrbitUtils.PI_2, SimpleKeplerOrbits.KeplerOrbitData.SemiMajorAxis.
bool SimpleKeplerOrbits.KeplerOrbitData.GetAscendingNode(out Vector3 asc)
Gets the ascending node of orbit.
asc The asc. true if ascending node exists, otherwise false
bool SimpleKeplerOrbits.KeplerOrbitData.GetAscendingNode(out Vector3d asc)
Gets the ascending node of orbit.
asc The asc. true if ascending node exists, otherwise false
References SimpleKeplerOrbits.KeplerOrbitData.CenterPoint, SimpleKeplerOrbits.KeplerOrbitUtils.Deg2Rad, SimpleKeplerOrbits.KeplerOrbitData.Eccentricity, SimpleKeplerOrbits.KeplerOrbitData.EclipticNormal, SimpleKeplerOrbits.KeplerOrbitData.GetFocalPositionAtEccentricAnomaly, SimpleKeplerOrbits.KeplerOrbitData.OrbitNormal, SimpleKeplerOrbits.KeplerOrbitData.SemiMajorAxisBasis.
bool SimpleKeplerOrbits.KeplerOrbitData.GetDescendingNode(out Vector3 desc)
Gets the descending node of orbit.
desc The desc. true if descending node exists, otherwise false
bool SimpleKeplerOrbits.KeplerOrbitData.GetDescendingNode(out Vector3d desc)
Gets the descending node orbit.
desc The desc. true if descending node exists, otherwise false
References SimpleKeplerOrbits.KeplerOrbitData.CenterPoint, SimpleKeplerOrbits.KeplerOrbitUtils.Deg2Rad, SimpleKeplerOrbits.KeplerOrbitData.Eccentricity, SimpleKeplerOrbits.KeplerOrbitData.EclipticNormal, SimpleKeplerOrbits.KeplerOrbitData.GetFocalPositionAtEccentricAnomaly, SimpleKeplerOrbits.KeplerOrbitData.OrbitNormal, SimpleKeplerOrbits.KeplerOrbitData.SemiMajorAxisBasis.
void SimpleKeplerOrbits.KeplerOrbitData.UpdateOrbitDataByTime(double deltaTime)
Updates the kepler orbit state by defined deltatime. Orbit main parameters will remains unchanged, but all anomalies will progress in time.
deltaTime The delta time.
References SimpleKeplerOrbits.KeplerOrbitData.SetPositionByCurrentAnomaly, SimpleKeplerOrbits.KeplerOrbitData.SetVelocityByCurrentAnomaly, SimpleKeplerOrbits.KeplerOrbitData.UpdateOrbitAnomaliesByTime.
void SimpleKeplerOrbits.KeplerOrbitData.UpdateOrbitAnomaliesByTime(double deltaTime)
Updates the value of orbital anomalies by defined deltatime.
deltaTime The delta time. Only anomalies values will be changed. Position and velocity states needs to be updated too after this method call.
References SimpleKeplerOrbits.KeplerOrbitData.AttractorMass, SimpleKeplerOrbits.KeplerOrbitData.EccentricAnomaly, SimpleKeplerOrbits.KeplerOrbitData.Eccentricity, SimpleKeplerOrbits.KeplerOrbitData.GravConst, SimpleKeplerOrbits.KeplerOrbitData.MeanAnomaly, SimpleKeplerOrbits.KeplerOrbitData.Period, SimpleKeplerOrbits.KeplerOrbitUtils.PI_2, SimpleKeplerOrbits.KeplerOrbitData.SemiMajorAxis, SimpleKeplerOrbits.KeplerOrbitData.TrueAnomaly.
Referenced by SimpleKeplerOrbits.KeplerOrbitData.UpdateOrbitDataByTime.
void SimpleKeplerOrbits.KeplerOrbitData.SetPositionByCurrentAnomaly()
Updates position from anomaly state.
References SimpleKeplerOrbits.KeplerOrbitData.EccentricAnomaly, SimpleKeplerOrbits.KeplerOrbitData.GetFocalPositionAtEccentricAnomaly, SimpleKeplerOrbits.KeplerOrbitData.Position.
Referenced by SimpleKeplerOrbits.KeplerOrbitData.SetEccentricAnomaly, SimpleKeplerOrbits.KeplerOrbitData.SetEccentricity, SimpleKeplerOrbits.KeplerOrbitData.SetMeanAnomaly, SimpleKeplerOrbits.KeplerOrbitData.SetTrueAnomaly, SimpleKeplerOrbits.KeplerOrbitData.UpdateOrbitDataByTime.
void SimpleKeplerOrbits.KeplerOrbitData.SetVelocityByCurrentAnomaly()
Sets velocity by current anomaly.
References SimpleKeplerOrbits.KeplerOrbitData.EccentricAnomaly, SimpleKeplerOrbits.KeplerOrbitData.GetVelocityAtEccentricAnomaly, SimpleKeplerOrbits.KeplerOrbitData.Velocity.
Referenced by SimpleKeplerOrbits.KeplerOrbitData.SetEccentricAnomaly, SimpleKeplerOrbits.KeplerOrbitData.SetEccentricity, SimpleKeplerOrbits.KeplerOrbitData.SetMeanAnomaly, SimpleKeplerOrbits.KeplerOrbitData.SetTrueAnomaly, SimpleKeplerOrbits.KeplerOrbitData.UpdateOrbitDataByTime.
void SimpleKeplerOrbits.KeplerOrbitData.SetEccentricity(double e)
Sets the eccentricity and updates all corresponding orbit state values.
e The new eccentricity value.
References SimpleKeplerOrbits.KeplerOrbitData.CalculateNewOrbitData, SimpleKeplerOrbits.KeplerOrbitData.CenterPoint, SimpleKeplerOrbits.KeplerOrbitData.EccentricAnomaly, SimpleKeplerOrbits.KeplerOrbitData.Eccentricity, SimpleKeplerOrbits.KeplerOrbitData.FocalParameter, SimpleKeplerOrbits.KeplerOrbitData.IsValidOrbit, SimpleKeplerOrbits.KeplerOrbitData.MeanAnomaly, SimpleKeplerOrbits.KeplerOrbitData.PeriapsisDistance, SimpleKeplerOrbits.KeplerOrbitData.SemiMajorAxis, SimpleKeplerOrbits.KeplerOrbitData.SemiMajorAxisBasis, SimpleKeplerOrbits.KeplerOrbitData.SemiMinorAxis, SimpleKeplerOrbits.KeplerOrbitData.SetPositionByCurrentAnomaly, SimpleKeplerOrbits.KeplerOrbitData.SetVelocityByCurrentAnomaly, SimpleKeplerOrbits.KeplerOrbitData.TrueAnomaly.
void SimpleKeplerOrbits.KeplerOrbitData.SetMeanAnomaly(double m)
Sets the mean anomaly and updates all other anomalies.
m The m.
References SimpleKeplerOrbits.KeplerOrbitData.EccentricAnomaly, SimpleKeplerOrbits.KeplerOrbitData.Eccentricity, SimpleKeplerOrbits.KeplerOrbitData.IsValidOrbit, SimpleKeplerOrbits.KeplerOrbitData.MeanAnomaly, SimpleKeplerOrbits.KeplerOrbitUtils.PI_2, SimpleKeplerOrbits.KeplerOrbitData.SetPositionByCurrentAnomaly, SimpleKeplerOrbits.KeplerOrbitData.SetVelocityByCurrentAnomaly, SimpleKeplerOrbits.KeplerOrbitData.TrueAnomaly.
void SimpleKeplerOrbits.KeplerOrbitData.SetTrueAnomaly(double t)
Sets the true anomaly and updates all other anomalies.
t The t.
References SimpleKeplerOrbits.KeplerOrbitData.EccentricAnomaly, SimpleKeplerOrbits.KeplerOrbitData.Eccentricity, SimpleKeplerOrbits.KeplerOrbitData.IsValidOrbit, SimpleKeplerOrbits.KeplerOrbitData.MeanAnomaly, SimpleKeplerOrbits.KeplerOrbitUtils.PI_2, SimpleKeplerOrbits.KeplerOrbitData.SetPositionByCurrentAnomaly, SimpleKeplerOrbits.KeplerOrbitData.SetVelocityByCurrentAnomaly.
void SimpleKeplerOrbits.KeplerOrbitData.SetEccentricAnomaly(double e)
Sets the eccentric anomaly and updates all other anomalies.
e The e.
References SimpleKeplerOrbits.KeplerOrbitData.EccentricAnomaly, SimpleKeplerOrbits.KeplerOrbitData.Eccentricity, SimpleKeplerOrbits.KeplerOrbitData.IsValidOrbit, SimpleKeplerOrbits.KeplerOrbitData.MeanAnomaly, SimpleKeplerOrbits.KeplerOrbitUtils.PI_2, SimpleKeplerOrbits.KeplerOrbitData.SetPositionByCurrentAnomaly, SimpleKeplerOrbits.KeplerOrbitData.SetVelocityByCurrentAnomaly, SimpleKeplerOrbits.KeplerOrbitData.TrueAnomaly.
void SimpleKeplerOrbits.KeplerOrbitData.RotateOrbit(Quaternion rotation)
Rotates the relative position and velocity by same quaternion.
rotation The rotation.
References SimpleKeplerOrbits.KeplerOrbitData.CalculateNewOrbitData, SimpleKeplerOrbits.KeplerOrbitData.Position, SimpleKeplerOrbits.KeplerOrbitData.Velocity.