SimpleKeplerOrbits::KeplerOrbitUtils
const double SimpleKeplerOrbits.KeplerOrbitUtils.PI_2
Two PI.
Referenced by SimpleKeplerOrbits.KeplerOrbitUtils.ConvertEccentricToTrueAnomaly, SimpleKeplerOrbits.KeplerOrbitUtils.ConvertTrueToEccentricAnomaly, SimpleKeplerOrbits.KeplerOrbitData.GetOrbitPoints, SimpleKeplerOrbits.KeplerOrbitData.GetOrbitPointsNoAlloc, SimpleKeplerOrbits.KeplerOrbitData.SetEccentricAnomaly, SimpleKeplerOrbits.KeplerOrbitData.SetMeanAnomaly, SimpleKeplerOrbits.KeplerOrbitData.SetTrueAnomaly, SimpleKeplerOrbits.KeplerOrbitData.UpdateOrbitAnomaliesByTime.
const double SimpleKeplerOrbits.KeplerOrbitUtils.Deg2Rad
Referenced by SimpleKeplerOrbits.KeplerOrbitData.CalculateNewOrbitData, SimpleKeplerOrbits.KeplerOrbitData.GetAscendingNode, SimpleKeplerOrbits.KeplerOrbitData.GetDescendingNode.
const double SimpleKeplerOrbits.KeplerOrbitUtils.Rad2Deg
const double SimpleKeplerOrbits.KeplerOrbitUtils.Epsilon
static double SimpleKeplerOrbits.KeplerOrbitUtils.Acosh(double x)
Regular Acosh, but without exception when out of possible range.
x The input value. Calculated Acos value or 0.
Referenced by SimpleKeplerOrbits.KeplerOrbitUtils.ConvertTrueToEccentricAnomaly.
static Vector3 SimpleKeplerOrbits.KeplerOrbitUtils.GetRayPlaneIntersectionPoint(Vector3 pointOnPlane, Vector3 normal, Vector3 rayOrigin, Vector3 rayDirection)
Gets the ray plane intersection point.
pointOnPlane The point on plane. normal The normal vector. rayOrigin The ray origin point. rayDirection The ray direction vector. Point on a plane, where ray is intersected with it.
References SimpleKeplerOrbits.KeplerOrbitUtils.DotProduct.
static Vector3 SimpleKeplerOrbits.KeplerOrbitUtils.RotateVectorByAngle(Vector3 v, float angleRad, Vector3 n)
Rotate vector around another vector
v Vector to rotate angleRad angle in radians n normalized vector to rotate around, or normal of rotation plane
static Vector3d SimpleKeplerOrbits.KeplerOrbitUtils.RotateVectorByAngle(Vector3d v, double angleRad, Vector3d n)
Rotate vector around another vector (double)
v Vector to rotate angleRad angle in radians n normalized vector to rotate around, or normal of rotation plane
References UnityEngine.Vector3d.x, UnityEngine.Vector3d.y, UnityEngine.Vector3d.z.
static float SimpleKeplerOrbits.KeplerOrbitUtils.DotProduct(Vector3 a, Vector3 b)
Dot product of two vectors.
a The first vector. b The second vector. Dot product.
Referenced by SimpleKeplerOrbits.KeplerOrbitData.CalculateNewOrbitData, SimpleKeplerOrbits.KeplerOrbitUtils.GetRayPlaneIntersectionPoint.
static double SimpleKeplerOrbits.KeplerOrbitUtils.DotProduct(Vector3d a, Vector3d b)
Dot product of two vectors.
a The first vector. b The second vector. Dot product.
static Vector3 SimpleKeplerOrbits.KeplerOrbitUtils.CrossProduct(Vector3 a, Vector3 b)
Cross product of two vectors.
a The first vector. b The second vector. Perpendicular vector.
Referenced by SimpleKeplerOrbits.KeplerOrbitUtils.CalcCircleOrbitVelocity, SimpleKeplerOrbits.KeplerOrbitUtils.CalcOrbitPoints, SimpleKeplerOrbits.KeplerOrbitData.CalculateNewOrbitData.
static Vector3d SimpleKeplerOrbits.KeplerOrbitUtils.CrossProduct(Vector3d a, Vector3d b)
Cross product of two vectors.
a The first vector. b The second vector. Perpendicular vector.
References UnityEngine.Vector3d.x, UnityEngine.Vector3d.y, UnityEngine.Vector3d.z.
static Vector3 SimpleKeplerOrbits.KeplerOrbitUtils.CalcCircleOrbitVelocity(Vector3 attractorPos, Vector3 bodyPos, double attractorMass, double bodyMass, Vector3 orbitNormal, double gConst)
Calc velocity vector for circle orbit.
References SimpleKeplerOrbits.KeplerOrbitUtils.CrossProduct.
static Vector3d SimpleKeplerOrbits.KeplerOrbitUtils.CalcCircleOrbitVelocity(Vector3d attractorPos, Vector3d bodyPos, double attractorMass, double bodyMass, Vector3d orbitNormal, double gConst)
Calc velocity vector for circle orbit.
References SimpleKeplerOrbits.KeplerOrbitUtils.CrossProduct.
static Vector3 [] SimpleKeplerOrbits.KeplerOrbitUtils.CalcOrbitPoints(Vector3 attractorPos, Vector3 bodyPos, double attractorMass, double bodyMass, Vector3 relVelocity, double gConst, int pointsCount)
Calc orbit curve points with provided precision.
References SimpleKeplerOrbits.KeplerOrbitUtils.CalcCenterOfMass, SimpleKeplerOrbits.KeplerOrbitUtils.CrossProduct.
static Vector3 SimpleKeplerOrbits.KeplerOrbitUtils.CalcCenterOfMass(Vector3 pos1, double mass1, Vector3 pos2, double mass2)
Calculates the center of mass.
pos1 The posistion 1. mass1 The mass 1. pos2 The position 2. mass2 The mass 2. Center of mass postion vector.
Referenced by SimpleKeplerOrbits.KeplerOrbitUtils.CalcOrbitPoints.
static Vector3d SimpleKeplerOrbits.KeplerOrbitUtils.CalcCenterOfMass(Vector3d pos1, double mass1, Vector3d pos2, double mass2)
Calculates the center of mass.
pos1 The posistion 1. mass1 The mass 1. pos2 The position 2. mass2 The mass 2. Center of mass postion vector.
static double SimpleKeplerOrbits.KeplerOrbitUtils.ConvertEccentricToTrueAnomaly(double eccentricAnomaly, double eccentricity)
Converts the eccentric to true anomaly.
eccentricAnomaly The eccentric anomaly. eccentricity The eccentricity. True anomaly in radians.
References SimpleKeplerOrbits.KeplerOrbitUtils.PI_2.
Referenced by SimpleKeplerOrbits.KeplerOrbitData.GetVelocityAtEccentricAnomaly.
static double SimpleKeplerOrbits.KeplerOrbitUtils.ConvertTrueToEccentricAnomaly(double trueAnomaly, double eccentricity)
Converts the true to eccentric anomaly.
trueAnomaly The true anomaly. eccentricity The eccentricity. Eccentric anomaly in radians.
References SimpleKeplerOrbits.KeplerOrbitUtils.Acosh, SimpleKeplerOrbits.KeplerOrbitUtils.PI_2.
static double SimpleKeplerOrbits.KeplerOrbitUtils.ConvertMeanToEccentricAnomaly(double meanAnomaly, double eccentricity)
Converts the mean to eccentric anomaly.
meanAnomaly The mean anomaly. eccentricity The eccentricity. Eccentric anomaly in radians.
References SimpleKeplerOrbits.KeplerOrbitUtils.KeplerSolver, SimpleKeplerOrbits.KeplerOrbitUtils.KeplerSolverHyperbolicCase.
static double SimpleKeplerOrbits.KeplerOrbitUtils.ConvertEccentricToMeanAnomaly(double eccentricAnomaly, double eccentricity)
Converts the eccentric to mean anomaly.
eccentricAnomaly The eccentric anomaly. eccentricity The eccentricity. Mean anomaly in radians.
static double SimpleKeplerOrbits.KeplerOrbitUtils.CalcTrueAnomalyForDistance(double distance, double eccentricity, double semiMajorAxis)
Gets the True anomaly value from current distance from the focus (attractor).
distance The distance from attractor. eccentricity The eccentricity. semiMajorAxis The semi major axis.
static double SimpleKeplerOrbits.KeplerOrbitUtils.KeplerSolver(double meanAnomaly, double eccentricity)
A classic Kepler solver.
meanAnomaly The mean anomaly in radians. eccentricity The eccentricity. Eccentric anomaly in radians.
Referenced by SimpleKeplerOrbits.KeplerOrbitUtils.ConvertMeanToEccentricAnomaly.
static double SimpleKeplerOrbits.KeplerOrbitUtils.KeplerSolverHyperbolicCase(double meanAnomaly, double eccentricity)
Kepler solver for hyperbolic case.
meanAnomaly The mean anomaly. eccentricity The eccentricity. Eccentric anomaly in radians.
Referenced by SimpleKeplerOrbits.KeplerOrbitUtils.ConvertMeanToEccentricAnomaly.